// Eventos da plataforma, fatiados de data.ts para a home carregar sob
// demanda (ProximosEventos) sem arrastar o catalogo inteiro. data.ts
// reexporta este array para os consumidores existentes.

/** Todos os estados + DF (sigla IBGE), para filtros e cadastro de eventos */
export const estadosBrasil: { sigla: string; nome: string }[] = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
].sort((a, b) => a.nome.localeCompare(b.nome, "pt-BR"));

/** Eventos online nacionais, itinerantes ou globais voltados ao público BR, use no campo `estado` */
export const EVENTO_UF_NACIONAL = "NA" as const;

export const eventos = [
  // TODO: adicionar mais eventos e webinars aqui via curadoria verificada
  // (eventos reais, com data e link oficial). Depende da Ana ou do Cowork
  // fornecer a lista; nao inventar evento. A home (ProximosEventos) ja le desta
  // fonte e mostra os proximos que tem link/material publico.
  {
    id: "campus-party",
    nome: "Campus Party Brasil",
    data: "Julho (anual)",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "Tecnologia Geral",
    valor: "Gratuito e pago",
    link: "https://brasil.campus-party.org",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=brasil.campus-party.org&sz=128",
    calendarStart: "20260701",
    calendarEnd: "20260705",
    descricao:
      "Um dos maiores eventos de tecnologia e inovação do mundo. Palestras, workshops, hackathons e networking.",
    organizador: "Campus Party",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "python-brasil",
    nome: "Python Brasil",
    data: "14 a 19 de outubro de 2026",
    horario: "Vários horários",
    cidade: "Florianópolis",
    estado: "SC",
    formato: "Híbrido",
    area: "Python / Dados / IA",
    valor: "Pago",
    link: "https://pythonbrasil.org.br",
    logoUrl: "https://www.google.com/s2/favicons?domain=python.org.br&sz=128",
    calendarStart: "20261014",
    calendarEnd: "20261019",
    descricao:
      "Maior conferência de Python da América Latina. Palestras, tutoriais e sprints de código.",
    organizador: "Associação Python Brasil",
    certificado: false,
    categoria: "Conferência",
  },
  {
    id: "women-in-tech",
    nome: "Women in Tech Summit",
    data: "Ao longo do ano",
    horario: "Vários horários",
    cidade: "São Paulo / Online",
    estado: "SP",
    formato: "Híbrido",
    area: "Carreira Tech",
    valor: "Gratuito e pago",
    link: "https://www.linkedin.com/search/results/events/?keywords=women+in+tech",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=women-in-tech.org&sz=128",
    calendarStart: "20260615",
    calendarEnd: "20260616",
    descricao:
      "Eventos focados em empoderar mulheres na tecnologia. Palestras, mentorias e networking.",
    organizador: "Diversas organizações",
    certificado: false,
    categoria: "Mulheres na Tecnologia",
  },
  {
    id: "meetup-react",
    nome: "React SP Meetup",
    data: "Mensal",
    horario: "19h",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Híbrido",
    area: "Front-end / React",
    valor: "Gratuito",
    link: "https://www.meetup.com/pt-BR/reactjs-sao-paulo/",
    logoUrl: "https://www.google.com/s2/favicons?domain=meetup.com&sz=128",
    calendarStart: "20260610T220000Z",
    calendarEnd: "20260611T000000Z",
    descricao:
      "Encontro mensal da comunidade React de São Paulo. Palestras técnicas e networking.",
    organizador: "Comunidade React SP",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "hacktoberfest",
    nome: "Hacktoberfest",
    data: "Outubro (anual)",
    horario: "Online: mês inteiro",
    cidade: "Online",
    estado: EVENTO_UF_NACIONAL,
    formato: "Online",
    area: "Programação / Open Source",
    valor: "Gratuito",
    link: "https://hacktoberfest.com",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=hacktoberfest.com&sz=128",
    calendarStart: "20261001",
    calendarEnd: "20261101",
    descricao:
      "Evento global de contribuição para projetos open source. Ótimo para portfólio e networking.",
    organizador: "DigitalOcean",
    certificado: false,
    categoria: "Hackathon / Open Source",
  },
  {
    id: "ux-conf-br",
    nome: "UX Conf BR",
    data: "Edição a confirmar",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "UX/UI Design",
    valor: "Pago",
    link: "https://uxconf.com.br",
    logoUrl: "https://www.google.com/s2/favicons?domain=uxconf.com.br&sz=128",
    calendarStart: "20260901",
    calendarEnd: "20260902",
    descricao:
      "Maior conferência de UX do Brasil. Palestras com profissionais nacionais e internacionais.",
    organizador: "UX Conf",
    certificado: false,
    categoria: "Conferência",
  },
  {
    id: "tdc",
    nome: "The Developer's Conference (TDC)",
    data: "Ao longo do ano",
    horario: "Vários horários",
    cidade: "São Paulo / Online",
    estado: "SP",
    formato: "Híbrido",
    area: "Desenvolvimento / Dados / Produto / DevOps",
    valor: "Pago",
    link: "https://thedevconf.com",
    logoUrl: "https://www.google.com/s2/favicons?domain=thedevconf.com&sz=128",
    calendarStart: "20260820",
    calendarEnd: "20260824",
    descricao:
      "Conferência brasileira com trilhas técnicas para desenvolvimento, dados, produto, arquitetura, carreira e liderança.",
    organizador: "TDC",
    certificado: false,
    categoria: "Conferência",
  },
  {
    id: "qcon-sao-paulo",
    nome: "QCon São Paulo",
    data: "Setembro 2026",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "Arquitetura / Engenharia de Software",
    valor: "Pago",
    link: "https://qconsf.com/sao-paulo",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=qconferences.com&sz=128",
    calendarStart: "20260914",
    calendarEnd: "20260918",
    descricao:
      "Evento para pessoas desenvolvedoras, arquitetas e lideranças técnicas com foco em sistemas em escala e engenharia moderna.",
    organizador: "InfoQ / QCon",
    certificado: false,
    categoria: "Conferência",
  },
  {
    id: "aws-summit-sp",
    nome: "AWS Summit São Paulo",
    data: "Agosto 2026",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "Cloud / DevOps / Dados / IA",
    valor: "Gratuito",
    link: "https://aws.amazon.com/pt/events/summits/sao-paulo/",
    logoUrl: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=128",
    calendarStart: "20260806",
    calendarEnd: "20260807",
    descricao:
      "Evento oficial da AWS com palestras, demos, sessões técnicas e networking sobre cloud, segurança, dados e IA.",
    organizador: "AWS",
    certificado: false,
    categoria: "Cloud",
  },
  {
    id: "google-cloud-summit",
    nome: "Google Cloud Summit Brasil",
    data: "Junho 2026",
    horario: "Vários horários",
    cidade: "São Paulo / Online",
    estado: "SP",
    formato: "Híbrido",
    area: "Cloud / Dados / IA",
    valor: "Gratuito",
    link: "https://cloud.google.com/events",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=cloud.google.com&sz=128",
    calendarStart: "20260618",
    calendarEnd: "20260619",
    descricao:
      "Evento com novidades, demonstrações e trilhas práticas sobre Google Cloud, IA generativa, dados e infraestrutura.",
    organizador: "Google Cloud",
    certificado: false,
    categoria: "Cloud",
  },
  {
    id: "devopsdays-sp",
    nome: "DevOpsDays São Paulo",
    data: "Maio 2026",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "DevOps / SRE / Cloud",
    valor: "Pago",
    link: "https://devopsdays.org",
    logoUrl: "https://www.google.com/s2/favicons?domain=devopsdays.org&sz=128",
    calendarStart: "20260522",
    calendarEnd: "20260524",
    descricao:
      "Encontro da comunidade DevOps com palestras, open spaces e debates sobre cultura, automação, confiabilidade e entrega contínua.",
    organizador: "DevOpsDays",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "front-in-sampa",
    nome: "Front in Sampa",
    data: "Novembro 2026",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "Front-end / JavaScript / UX",
    valor: "Pago",
    link: "https://frontinsampa.com.br",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=frontinsampa.com.br&sz=128",
    calendarStart: "20261107",
    calendarEnd: "20261108",
    descricao:
      "Evento brasileiro focado em front-end, JavaScript, acessibilidade, performance, design e carreira.",
    organizador: "Front in Sampa",
    certificado: false,
    categoria: "Conferência",
  },
  {
    id: "data-hackers-meetup",
    nome: "Data Hackers Meetup",
    data: "Mensal",
    horario: "19h",
    cidade: "Online",
    estado: EVENTO_UF_NACIONAL,
    formato: "Online",
    area: "Dados / IA / Analytics",
    valor: "Gratuito",
    link: "https://www.meetup.com/data-hackers/",
    logoUrl: "https://www.google.com/s2/favicons?domain=meetup.com&sz=128",
    calendarStart: "20260625T220000Z",
    calendarEnd: "20260626T000000Z",
    descricao:
      "Encontro da comunidade de dados com talks, troca de experiências e conteúdo sobre análise, engenharia, ciência de dados e IA.",
    organizador: "Data Hackers",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "gdg-rio-tech-talks",
    nome: "Google Developer Groups Tech Talks: Rio",
    data: "Mensal",
    horario: "19h30",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    formato: "Híbrido",
    area: "Mobile / Cloud / IA",
    valor: "Gratuito",
    link: "https://gdg.community.dev/gdg-rio-de-janeiro/",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=developers.google.com&sz=128",
    calendarStart: "20260603T223000",
    calendarEnd: "20260603T013000",
    descricao:
      "Meetups mensais sobre Android, Firebase, IA com ferramentas Google e tecnologias relacionadas.",
    organizador: "GDG Rio de Janeiro",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "bh-tech-talks",
    nome: "BH Tech Meetup",
    data: "Quinzenal",
    horario: "19h",
    cidade: "Belo Horizonte",
    estado: "MG",
    formato: "Presencial",
    area: "Produto / Dados / Engenharia",
    valor: "Gratuito",
    link: "https://www.sympla.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=sympla.com.br&sz=128",
    calendarStart: "20260612",
    calendarEnd: "20260613",
    descricao:
      "Encontro da comunidade de tecnologia mineira com debates sobre dados, IA, carreira em produto e engenharia.",
    organizador: "BH Tech Meetup",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "tchelinux-poa",
    nome: "Tchelinux Porto Alegre",
    data: "Mensal",
    horario: "14h às 18h",
    cidade: "Porto Alegre",
    estado: "RS",
    formato: "Presencial",
    area: "Linux / Segurança / Open Source",
    valor: "Gratuito",
    link: "https://tchelinux.org/",
    logoUrl: "https://www.google.com/s2/favicons?domain=tchelinux.org&sz=128",
    calendarStart: "20260705",
    calendarEnd: "20260706",
    descricao:
      "Eventos gratuitos sobre software livre e cultura hacker no Rio Grande do Sul: palestras técnicas e troca entre comunidades.",
    organizador: "Tchelinux",
    certificado: false,
    categoria: "Comunidades / OSS",
  },
  {
    id: "gdg-curitiba",
    nome: "Google Developer Groups Meetup Curitiba",
    data: "Mensal",
    horario: "19h",
    cidade: "Curitiba",
    estado: "PR",
    formato: "Híbrido",
    area: "Web / Cloud / Carreira Tech",
    valor: "Gratuito",
    link: "https://gdg.community.dev/",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=developers.google.com&sz=128",
    calendarStart: "20260617T224500",
    calendarEnd: "20260618T023000",
    descricao:
      "Comunidade paranaense com demos de Gemini, GCP, desenvolvimento web moderno e boas práticas de carreira.",
    organizador: "GDG Curitiba",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "front-floripa-meet",
    nome: "Front-End Floripa",
    data: "Mensal",
    horario: "18h45",
    cidade: "Florianópolis",
    estado: "SC",
    formato: "Presencial",
    area: "Front-end / React / UX",
    valor: "Gratuito",
    link: "https://www.meetup.com/",
    logoUrl: "https://www.google.com/s2/favicons?domain=meetup.com&sz=128",
    calendarStart: "20260608T223000",
    calendarEnd: "20260609T023000",
    descricao:
      "Encontro catarinense sobre HTML, CSS, JavaScript e ecossistema front-end na Ilha da Magia.",
    organizador: "Comunidade Front-end Floripa",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "conexao-dados-df",
    nome: "Conexão Informação Brasília: Dados públicos em prática",
    data: "Setembro 2026",
    horario: "9h às 17h",
    cidade: "Brasília",
    estado: "DF",
    formato: "Híbrido",
    area: "Dados abertos / Governo / Analytics",
    valor: "Gratuito",
    link: "https://www.sympla.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=gov.br&sz=128",
    calendarStart: "20260912",
    calendarEnd: "20260913",
    descricao:
      "Debates sobre transparência, dados públicos federativos e ferramentas de análise com foco na administração pública.",
    organizador: "Coletivo dados.gov.br advocates",
    certificado: false,
    categoria: "Carreira GovTech",
  },
  {
    id: "natal-js",
    nome: "Natal.js",
    data: "Bimestral",
    horario: "19h",
    cidade: "Natal",
    estado: "RN",
    formato: "Presencial",
    area: "JavaScript / Node / Front-end",
    valor: "Gratuito",
    link: "https://nataljs.github.io/",
    logoUrl: "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    calendarStart: "20260620",
    calendarEnd: "20260621",
    descricao:
      "Meetup nordestino de JavaScript e ecossistema web: projetos livres, vagas remotas e oficinas colaborativas.",
    organizador: "Natal.js",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "salvador-python",
    nome: "Python Nordeste: Trilhas em Salvador",
    data: "Novembro 2026",
    horario: "Vários horários",
    cidade: "Salvador",
    estado: "BA",
    formato: "Híbrido",
    area: "Python / Dados / Educação",
    valor: "Pago solidário",
    link: "https://python.org.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=python.org.br&sz=128",
    calendarStart: "20261106",
    calendarEnd: "20261107",
    descricao:
      "Encontros regionais alinhados à comunidade Python Brasil: tutoriais, mesas LGBTQIA+ em tech e mostra de projetos baianos.",
    organizador: "Python Nordeste + Afiliadas",
    certificado: false,
    categoria: "Conferência",
  },
  {
    id: "manaus-ai-dev",
    nome: "Amazon Dev Day Manaus",
    data: "Agosto 2026",
    horario: "8h às 18h30",
    cidade: "Manaus",
    estado: "AM",
    formato: "Presencial",
    area: "Cloud / IA / IoT amazônicos",
    valor: "Gratuito",
    link: "https://aws.amazon.com/pt/events/",
    logoUrl: "https://www.google.com/s2/favicons?domain=amazon.com.br&sz=128",
    calendarStart: "20260807",
    calendarEnd: "20260807",
    descricao:
      "Imersões presenciais em edge computing, dados ambientais em nuvem e carreiras tecnológicas na região Norte.",
    organizador: "Comunidades locais · parceiros cloud",
    certificado: false,
    categoria: "Hackathon",
  },
  {
    id: "brasilia-blocks",
    nome: "Brasília Web3 Builders",
    data: "Mensal",
    horario: "20h",
    cidade: "Brasília",
    estado: "DF",
    formato: "Online",
    area: "Blockchain / segurança / contratos inteligentes",
    valor: "Gratuito",
    link: "https://discord.com/",
    logoUrl: "https://www.google.com/s2/favicons?domain=discord.com&sz=128",
    calendarStart: "20260618T231500",
    calendarEnd: "20260618T234500",
    descricao:
      "Oficinas introdutórias sobre smart contracts conscientes da Regulação LGPD aplicada ao ecossistema descentralizado.",
    organizador: "Brasília Web3 Builders",
    certificado: false,
    categoria: "Hackathon",
  },
  {
    id: "belem-geek-festival",
    nome: "Pará Geek Connect",
    data: "Outubro 2026",
    horario: "10h às 19h",
    cidade: "Belém",
    estado: "PA",
    formato: "Presencial",
    area: "Games / dados culturais / maker",
    valor: "Gratuito na comunidade",
    link: "https://www.sympla.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=sympla.com.br&sz=128",
    calendarStart: "20261003",
    calendarEnd: "20261003",
    descricao:
      "Mostra amazônica de makers, projetos indie e tecnologia inclusiva com vagas paralelas para periferias metropolitanas.",
    organizador: "Coletivos Pará Tech",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "goiania-backend",
    nome: "Goiás Back-end Nights",
    data: "Quinzenal",
    horario: "19h45",
    cidade: "Goiânia",
    estado: "GO",
    formato: "Híbrido",
    area: "API / Arquitetura / Go & Node",
    valor: "Gratuito",
    link: "https://www.meetup.com/",
    logoUrl: "https://www.google.com/s2/favicons?domain=meetup.com&sz=128",
    calendarStart: "20260614",
    calendarEnd: "20260614",
    descricao:
      "Painéis rápidos sobre performance de APIs serverless vs monolitos modulados e segurança de integrações públicas estaduais.",
    organizador: "Golang & Node Goiás",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "fortaleza-ux-lab",
    nome: "Fortaleza UX Lab",
    data: "Mensal",
    horario: "18h",
    cidade: "Fortaleza",
    estado: "CE",
    formato: "Presencial",
    area: "Pesquisa UX / inclusão digital",
    valor: "Gratuito",
    link: "https://www.sympla.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=figma.com&sz=128",
    calendarStart: "20260621",
    calendarEnd: "20260621",
    descricao:
      "Laboratório aberto para testes de usabilidade com públicos periféricos e design system governamental simplificado.",
    organizador: "UX CE Coletiva",
    certificado: false,
    categoria: "Workshop",
  },
  {
    id: "pantanal-ai-lab-ms",
    nome: "Mato Grosso do Sul Responsible AI Sandbox",
    data: "Dezembro 2026",
    horario: "9h às 16h30",
    cidade: "Campo Grande",
    estado: "MS",
    formato: "Presencial",
    area: "IA responsável · bioinformática agrícola",
    valor: "Pago institucional",
    link: "https://aws.amazon.com/pt/events/",
    logoUrl: "https://www.google.com/s2/favicons?domain=amazon.com&sz=128",
    calendarStart: "20261202",
    calendarEnd: "20261203",
    descricao:
      "Laboratório com governança de modelos aplicados ao Pantanal Sul e estudos reproducíveis sob ética territorial.",
    organizador: "Parque Tec Bio MS",
    certificado: true,
    categoria: "Workshop",
  },
  {
    id: "teresina-ai-fair",
    nome: "Piauí Makers & IA",
    data: "Março 2027",
    horario: "10h às 18h",
    cidade: "Teresina",
    estado: "PI",
    formato: "Híbrido",
    area: "Robótica educacional · IA criativa",
    valor: "Gratuito público estudantil",
    link: "https://www.sympla.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=sympla.com.br&sz=128",
    calendarStart: "20270312",
    calendarEnd: "20270313",
    descricao:
      "Feira com laboratório de robótica lógica usando sucata eletrônica e oficinas de IA generativa acessível em escolas estaduais.",
    organizador: "Rede Makers Piauí",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "aracaju-qa-nights",
    nome: "Aracaju QA & Test Craft",
    data: "Mensal",
    horario: "18h45",
    cidade: "Aracaju",
    estado: "SE",
    formato: "Online",
    area: "Qualidade · automação Cypress",
    valor: "Gratuito",
    link: "https://discord.com/",
    logoUrl: "https://www.google.com/s2/favicons?domain=cypress.io&sz=128",
    calendarStart: "20260611T223000",
    calendarEnd: "20260611T233000",
    descricao:
      "Série online Sergipe-Brasil sobre shift-left testing, mocks resilientes para APIs públicas estaduais e observabilidade de testes flaky.",
    organizador: "Sergipe Test Guild",
    certificado: false,
    categoria: "Meetup",
  },
  {
    id: "macapa-edge-lab",
    nome: "Amapá Edge & Satélites Conectividade",
    data: "Janeiro 2027",
    horario: "9h às 17h",
    cidade: "Macapá",
    estado: "AP",
    formato: "Híbrido",
    area: "Edge IoT norte / comunicações",
    valor: "Pago institucional",
    link: "https://aws.amazon.com/pt/events/",
    logoUrl: "https://www.google.com/s2/favicons?domain=amazon.com&sz=128",
    calendarStart: "20270118",
    calendarEnd: "20270118",
    descricao:
      "Hackathon norte sobre backhaul satelital, telemetrias florestais resilientes offline e segurança de firmware em gateways edge.",
    organizador: "Edge Norte Lab",
    certificado: true,
    categoria: "Hackathon",
  },
  {
    id: "rio-branco-green-stack",
    nome: "Acre Green Stack Sprint",
    data: "Junho 2027",
    horario: "8h às 16h45",
    cidade: "Rio Branco",
    estado: "AC",
    formato: "Presencial",
    area: "Sustentabilidade computacional · low-power",
    valor: "Subvenção institucional",
    link: "https://www.sympla.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=gov.br&sz=128",
    calendarStart: "20270610",
    calendarEnd: "20270611",
    descricao:
      "Hackathon amazônico com foco energia distribuída, sensores soberanos e relatórios de carbono integrados a dashboards abertos estaduais.",
    organizador: "AC Green Developers",
    certificado: true,
    categoria: "Hackathon",
  },
  {
    id: "palmas-hack-city",
    nome: "Tocantins Code & Cidades",
    data: "Julho 2027",
    horario: "8h às 19h45",
    cidade: "Palmas",
    estado: "TO",
    formato: "Híbrido",
    area: "Cidades inteligentes / dados públicos estaduais",
    valor: "Gratuito",
    link: "https://gov.br/pt-br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=gov.br&sz=128",
    calendarStart: "20270721",
    calendarEnd: "20270721",
    descricao:
      "Marathon cívico usando APIs estaduais: mobilidade cicloviária inteligente, energia distribuída e telemedicina territorial.",
    organizador: "Secretaria Parceira TI Tocantins",
    certificado: true,
    categoria: "Hackathon",
  },
  {
    id: "sao-luis-maker-fair-ma",
    nome: "Maranhão Makers & Inclusion Fair",
    data: "Setembro 2027",
    horario: "9h às 20h",
    cidade: "São Luís",
    estado: "MA",
    formato: "Presencial",
    area: "Maker educacional · acessibilidade digital",
    valor: "Entrada gratuita projetos estudantis",
    link: "https://www.sympla.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=sympla.com.br&sz=128",
    calendarStart: "20270917",
    calendarEnd: "20270917",
    descricao:
      "Feira norte com zonas táteis/braille em hardware aberto e laboratório de audiodescrição em apps governamentais maranhenses.",
    organizador: "MA Inclusion Makers",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "joao-pessoa-privacy-forum-pb",
    nome: "João Pessoa LGPD Builders Forum",
    data: "Agosto 2027",
    horario: "8h30 às 18h40",
    cidade: "João Pessoa",
    estado: "PB",
    formato: "Híbrido",
    area: "Privacidade dados / segurança jurídica",
    valor: "Pago institucional",
    link: "https://www.gov.br/planalto/",
    logoUrl: "https://www.google.com/s2/favicons?domain=gov.br&sz=128",
    calendarStart: "20270821",
    calendarEnd: "20270821",
    descricao:
      "Fórum com times jurídico-técnicos estaduais praticando DPIA colaborativo, DPIA público estadual LGPD-compliant e playbook multilíngue.",
    organizador: "PB Builders Privacy",
    certificado: false,
    categoria: "Carreira GovTech",
  },
  {
    id: "rec-n-play",
    nome: "Rec'n'Play",
    data: "11 a 14 de novembro de 2026",
    horario: "Vários horários",
    cidade: "Recife",
    estado: "PE",
    formato: "Presencial",
    area: "Tecnologia / Inovação / Carreira",
    valor: "Gratuito",
    link: "https://recnplay.pe/",
    logoUrl: "https://www.google.com/s2/favicons?domain=recnplay.pe&sz=128",
    calendarStart: "20261111",
    calendarEnd: "20261114",
    descricao:
      "O maior festival gratuito de tecnologia e inovação do Brasil, no centro histórico do Recife. Palestras, workshops, oficinas e atrações culturais, com inscrição gratuita.",
    organizador: "Porto Digital e Sebrae Pernambuco",
    certificado: true,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "rio-innovation-week",
    nome: "Rio Innovation Week",
    data: "4 a 7 de agosto de 2026",
    horario: "Vários horários",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    formato: "Presencial",
    area: "Inovação / Tecnologia / IA",
    valor: "Pago",
    link: "https://rioinnovationweek.com.br/",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=rioinnovationweek.com.br&sz=128",
    calendarStart: "20260804",
    calendarEnd: "20260807",
    descricao:
      "Um dos maiores eventos de inovação da América Latina, no Pier Mauá. Dezenas de palcos com IA, desenvolvimento, robótica e educação digital.",
    organizador: "Rio Innovation Week",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "febraban-tech",
    nome: "FEBRABAN TECH",
    data: "24 a 26 de agosto de 2026",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "Tecnologia Bancária / IA / Segurança",
    valor: "Pago",
    link: "https://febrabantech.febraban.org.br/",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=febrabantech.febraban.org.br&sz=128",
    calendarStart: "20260824",
    calendarEnd: "20260826",
    descricao:
      "O maior evento de tecnologia bancária e financeira do país, debatendo IA, open finance e segurança cibernética.",
    organizador: "Federação Brasileira de Bancos",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "startup-summit",
    nome: "Startup Summit",
    data: "26 a 28 de agosto de 2026",
    horario: "Vários horários",
    cidade: "Florianópolis",
    estado: "SC",
    formato: "Presencial",
    area: "Startups / Produto / Inovação",
    valor: "Pago",
    link: "https://www.startupsummit.com.br/",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=startupsummit.com.br&sz=128",
    calendarStart: "20260826",
    calendarEnd: "20260828",
    descricao:
      "Principal encontro brasileiro de startups, no Centrosul. Três dias de palestras, investidores e trilhas sobre produto digital e tecnologia.",
    organizador: "Sebrae SC e Acate",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "hacktown",
    nome: "HackTown",
    data: "3 a 7 de setembro de 2026",
    horario: "Vários horários",
    cidade: "Santa Rita do Sapucaí",
    estado: "MG",
    formato: "Presencial",
    area: "Inovação / Tecnologia / Design",
    valor: "Pago",
    link: "https://hacktown.com.br/",
    logoUrl: "https://www.google.com/s2/favicons?domain=hacktown.com.br&sz=128",
    calendarStart: "20260903",
    calendarEnd: "20260907",
    descricao:
      "Festival que transforma a cidade inteira em ambiente de aprendizado, com palestras e workshops de tecnologia, criatividade e carreira.",
    organizador: "HackTown",
    certificado: false,
    categoria: "Feira de Tecnologia",
  },
  {
    id: "futurecom",
    nome: "Futurecom",
    data: "6 a 8 de outubro de 2026",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "Cloud / Conectividade / Cibersegurança",
    valor: "Pago",
    link: "https://www.futurecom.com.br/",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=futurecom.com.br&sz=128",
    calendarStart: "20261006",
    calendarEnd: "20261008",
    descricao:
      "Referência em conectividade e infraestrutura digital na América Latina, no São Paulo Expo. Debates sobre IA, cloud, cibersegurança e dados.",
    organizador: "Futurecom",
    certificado: false,
    categoria: "Conferência",
  },
  {
    id: "mindthesec-sp",
    nome: "Mind The Sec",
    data: "15 a 17 de setembro de 2026",
    horario: "Vários horários",
    cidade: "São Paulo",
    estado: "SP",
    formato: "Presencial",
    area: "Cibersegurança / AppSec",
    valor: "Pago",
    link: "https://www.mindthesec.com.br/",
    logoUrl:
      "https://www.google.com/s2/favicons?domain=mindthesec.com.br&sz=128",
    calendarStart: "20260915",
    calendarEnd: "20260917",
    descricao:
      "O maior evento de segurança da informação do Hemisfério Sul, no Transamérica Expo Center. Trilhas de cibersegurança, privacidade e compliance.",
    organizador: "Mind The Sec",
    certificado: true,
    categoria: "Conferência",
  },
];

