export const creatorHandle = "@ana.natech";

/** Foto de perfil da curadora Ana Moura (@ana.natech · via Unavatar/Instagram público). */
export const creatorPhotoUrl = "https://unavatar.io/instagram/ana.natech";

export const tipCategories = [
  "Dicas gerais",
  "Dicas de rotina",
  "Dicas de carreira",
  "Dicas de mercado",
  "Dicas de portfólio",
];

export const tipsArticles = [
  {
    id: "gerais-primeiros-passos",
    category: "Dicas gerais",
    title: "Como começar em tecnologia sem se perder",
    author: "Ana Moura",
    credit: "Curadoria BORA NA TECH?",
    summary: "Um guia direto para escolher uma primeira área, organizar estudos e evitar excesso de abas abertas.",
    youtube: "Curso em Vídeo: primeiros passos em programação",
    url: "https://www.youtube.com/@CursoemVideo",
  },
  {
    id: "rotina-estudos",
    category: "Dicas de rotina",
    title: "Rotina realista para estudar trabalhando ou cuidando da casa",
    author: "Rafaella Ballerini",
    credit: "Inspirado em conteúdos públicos da comunidade dev",
    summary: "Blocos curtos, revisão semanal e projeto pequeno para transformar estudo em entrega visível.",
    youtube: "Rafaella Ballerini: rotina e carreira dev",
    url: "https://www.youtube.com/@rafaellaballerini",
  },
  {
    id: "carreira-linkedin",
    category: "Dicas de carreira",
    title: "LinkedIn para primeira oportunidade",
    author: "Gabriela Serpa",
    credit: "Referência de carreira e posicionamento profissional",
    summary: "Como escrever título, sobre e posts mesmo sem experiência formal em tecnologia.",
    youtube: "Dicas de LinkedIn para iniciantes",
    url: "https://www.youtube.com/results?search_query=linkedin+para+iniciantes+tecnologia",
  },
  {
    id: "mercado-vagas",
    category: "Dicas de mercado",
    title: "Como ler vagas sem se assustar com a lista de requisitos",
    author: "Loiane Groner",
    credit: "Referência brasileira em educação tech",
    summary: "Entenda requisitos essenciais, desejáveis e sinais de vagas boas para estágio, trainee ou júnior.",
    youtube: "Loiane Groner: carreira em tecnologia",
    url: "https://www.youtube.com/@loianegroner",
  },
  {
    id: "portfolio-readme",
    category: "Dicas de portfólio",
    title: "README que explica seu projeto sem entrevista",
    author: "Camila Cavalcante",
    credit: "Curadoria de boas práticas GitHub",
    summary: "Estrutura simples para mostrar objetivo, prints, tecnologias, aprendizados e próximos passos.",
    youtube: "Como fazer README no GitHub",
    url: "https://www.youtube.com/results?search_query=como+fazer+readme+github+portfolio",
  },
];

export const womenArea = {
  tips: [
    "Procure comunidades com moderação ativa e canais para iniciantes.",
    "Monte uma rede pequena de apoio: uma pessoa para tirar dúvidas, uma para revisar currículo e uma para compartilhar vagas.",
    "Guarde evidências do seu aprendizado: posts, commits, prints e pequenos projetos.",
    "Priorize ambientes que tenham código de conduta claro e pessoas moderadoras visíveis.",
    "Use grupos de mulheres para revisar currículo, simular entrevista e entender faixas salariais.",
    "Não espere se sentir 100% pronta: aplique para vagas quando cumprir parte dos requisitos principais.",
  ],
  communities: [
    { name: "{reprograma}", desc: "Cursos e comunidade para mulheres em tecnologia.", url: "https://reprograma.com.br" },
    { name: "WoMakersCode", desc: "Comunidade, eventos e capacitação para mulheres.", url: "https://womakerscode.org" },
    { name: "PyLadies Brasil", desc: "Comunidade para mulheres que estudam Python.", url: "https://brasil.pyladies.com" },
    { name: "MariaLab", desc: "Coletivo feminista de tecnologia, autonomia digital e segurança.", url: "https://marialab.org" },
    { name: "Minas Programam", desc: "Iniciativa para formação e inclusão de mulheres na programação.", url: "https://minasprogramam.com" },
    { name: "Women Techmakers", desc: "Programa global do Google com eventos, histórias e recursos para mulheres em tecnologia.", url: "https://www.womentechmakers.com" },
  ],
  creators: [
    {
      name: "Ana Moura",
      handle: creatorHandle,
      topic: "Curadoria tech, primeiro passos e referências sem enrolação.",
      url: "https://www.instagram.com/ana.natech/",
      avatarUrl: creatorPhotoUrl,
    },
    {
      name: "Rafaella Ballerini",
      handle: "@rafaballerini",
      topic: "Programação, carreira e comunidade",
      url: "https://www.youtube.com/@rafaellaballerini",
      avatarUrl: "https://unavatar.io/youtube/rafaellaballerini",
    },
    {
      name: "Loiane Groner",
      handle: "@loianegroner",
      topic: "Java, Angular e carreira",
      url: "https://www.youtube.com/@loianegroner",
      avatarUrl: "https://unavatar.io/youtube/loianegroner",
    },
    {
      name: "Glaucia Lemos",
      handle: "@glaucia_lemos86",
      topic: "Cloud, Microsoft e educação",
      url: "https://www.youtube.com/results?search_query=Glaucia+Lemos+cloud",
      avatarUrl: "https://unavatar.io/youtube/GlauciaLemos",
    },
    {
      name: "Gabriela Pinheiro",
      handle: "@gabrielapinheiro",
      topic: "Front-end, educação e transição de carreira",
      url: "https://www.youtube.com/results?search_query=Gabriela+Pinheiro+programa%C3%A7%C3%A3o",
      avatarUrl: "https://unavatar.io/youtube/gabrielapinheiro",
    },
    {
      name: "Camila Cavalcante",
      handle: "@cami-la",
      topic: "Comunidade, GitHub, carreira e diversidade",
      url: "https://www.linkedin.com/in/camila-cavalcante/",
      avatarUrl: "https://unavatar.io/linkedin.com/in/camila-cavalcante",
    },
    {
      name: "Letícia Caires",
      handle: "@leticiascaires",
      topic: "Produto, carreira e bastidores de tecnologia",
      url: "https://www.linkedin.com/search/results/content/?keywords=Leticia%20Caires%20produto%20tech",
      avatarUrl: "https://unavatar.io/linkedin.com/in/leticiascaires",
    },
  ],
  videos: [
    { title: "Mulheres em tecnologia: primeiros passos", url: "https://www.youtube.com/results?search_query=mulheres+em+tecnologia+primeiros+passos" },
    { title: "Como construir portfólio iniciante", url: "https://www.youtube.com/results?search_query=portfolio+iniciante+programacao+mulheres" },
    { title: "Síndrome da impostora na tecnologia", url: "https://www.youtube.com/results?search_query=sindrome+da+impostora+mulheres+tecnologia" },
    { title: "Como se posicionar em tecnologia", url: "https://www.youtube.com/results?search_query=mulheres+tecnologia+marca+pessoal+linkedin" },
  ],
  affirmativeJobs: [
    { name: "Programathor - vagas afirmativas", url: "https://programathor.com.br/jobs" },
    { name: "Gupy - vagas para mulheres em tecnologia", url: "https://portal.gupy.io" },
    { name: "LinkedIn - mulheres em tecnologia", url: "https://www.linkedin.com/jobs/" },
    { name: "Telegram e LinkedIn de comunidades femininas", url: "https://www.linkedin.com/search/results/groups/?keywords=mulheres%20tecnologia" },
    { name: "Programas de estágio afirmativos", url: "https://www.google.com/search?q=programa+est%C3%A1gio+mulheres+tecnologia" },
  ],
  supportTracks: [
    { title: "Rede e comunidade", desc: "Participe de grupos onde possa pedir revisão de currículo, tirar dúvidas pontuais e trocar indicações de vagas." },
    { title: "Segurança e confiança", desc: "Busque comunidades com código de conduta, canais moderados e acolhimento para perguntas iniciantes." },
    { title: "Visibilidade profissional", desc: "Publique aprendizados pequenos, registre projetos e mantenha LinkedIn/GitHub com contexto." },
    { title: "Negociação e salário", desc: "Converse sobre faixas, benefícios e modelo de trabalho antes de aceitar propostas." },
  ],
  scholarshipPrograms: [
    { name: "Bolsas e bootcamps para mulheres", desc: "Pesquise programas sazonais de empresas, comunidades e escolas com turmas afirmativas.", url: "https://www.google.com/search?q=bolsas+bootcamp+mulheres+tecnologia" },
    { name: "Editais de comunidades", desc: "Acompanhe posts de comunidades femininas, pois muitas oportunidades aparecem primeiro nelas.", url: "https://www.linkedin.com/search/results/content/?keywords=bolsa%20mulheres%20tecnologia" },
    { name: "Eventos e encontros de comunidade", desc: "Hackathons, meetups e eventos online costumam reunir vagas, bolsas e grupos de estudo.", url: "https://www.sympla.com.br/eventos?s=mulheres%20tecnologia" },
  ],
  safeSpaceChecklist: [
    "Existe código de conduta ou regras de convivência visíveis.",
    "Há moderação ativa e canal para reportar problemas.",
    "Iniciantes são acolhidas sem piadas ou respostas agressivas.",
    "A comunidade compartilha oportunidades, referências e apoio prático.",
  ],
};

export const dictionaryTerms = [
  { term: "API", category: "Back-end", tags: ["Back-end", "Programação"], meaning: "Um caminho para sistemas conversarem entre si e trocarem dados." },
  { term: "Deploy", category: "DevOps", tags: ["DevOps", "Carreira"], meaning: "Publicar um site, app ou API para que outras pessoas consigam acessar." },
  { term: "Framework", category: "Programação", tags: ["Programação", "Front-end", "Back-end"], meaning: "Um conjunto de ferramentas e padrões que acelera a construção de software." },
  { term: "Git", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Sistema que registra versões do código e ajuda a colaborar em projetos." },
  { term: "GitHub", category: "Ferramentas", tags: ["Ferramentas", "Portfólio"], meaning: "Plataforma para hospedar código, colaborar em projetos e mostrar seu portfólio técnico." },
  { term: "Responsividade", category: "Front-end", tags: ["Front-end", "Design"], meaning: "Capacidade de uma interface se adaptar bem a celular, tablet e computador." },
  { term: "HTML", category: "Front-end", tags: ["Front-end", "Programação"], meaning: "Linguagem de marcação usada para estruturar páginas web com títulos, textos, imagens e links." },
  { term: "CSS", category: "Front-end", tags: ["Front-end", "Design"], meaning: "Linguagem usada para definir cores, espaçamentos, fontes, layout e aparência de páginas web." },
  { term: "JavaScript", category: "Front-end", tags: ["Front-end", "Programação"], meaning: "Linguagem que adiciona interatividade a sites e também pode ser usada no back-end com Node.js." },
  { term: "React", category: "Front-end", tags: ["Front-end", "Framework"], meaning: "Biblioteca JavaScript para criar interfaces a partir de componentes reutilizáveis." },
  { term: "DOM", category: "Front-end", tags: ["Front-end", "Programação"], meaning: "Representação da página no navegador que o JavaScript consegue ler e modificar." },
  { term: "Endpoint", category: "Back-end", tags: ["Back-end", "API"], meaning: "Endereço específico de uma API usado para buscar, criar, atualizar ou remover informações." },
  { term: "REST", category: "Back-end", tags: ["Back-end", "API"], meaning: "Estilo de arquitetura comum para APIs que usam métodos como GET, POST, PUT e DELETE." },
  { term: "JSON", category: "Back-end", tags: ["Back-end", "Dados"], meaning: "Formato leve de texto usado para enviar dados entre sistemas, muito comum em APIs." },
  { term: "Autenticação", category: "Segurança", tags: ["Segurança", "Back-end"], meaning: "Processo de confirmar quem é a pessoa usuária, geralmente com login, senha ou provedor externo." },
  { term: "Autorização", category: "Segurança", tags: ["Segurança", "Back-end"], meaning: "Regra que define o que uma pessoa autenticada pode acessar ou fazer dentro de um sistema." },
  { term: "Banco de dados", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Sistema usado para armazenar, organizar e consultar informações de uma aplicação." },
  { term: "SQL", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Linguagem usada para consultar e manipular dados em bancos relacionais." },
  { term: "Dataset", category: "Dados", tags: ["Dados", "IA"], meaning: "Conjunto de dados usado para análise, visualização ou treinamento de modelos." },
  { term: "Dashboard", category: "Dados", tags: ["Dados", "Produto"], meaning: "Painel visual com métricas, gráficos e indicadores para acompanhar uma situação ou decisão." },
  { term: "Machine Learning", category: "IA", tags: ["IA", "Dados"], meaning: "Área da IA em que sistemas aprendem padrões a partir de dados para fazer previsões ou classificações." },
  { term: "Modelo", category: "IA", tags: ["IA", "Dados"], meaning: "Resultado de um treinamento de machine learning usado para responder, prever ou classificar algo." },
  { term: "Prompt", category: "IA", tags: ["IA", "Produtividade"], meaning: "Instrução escrita para orientar uma ferramenta de IA a gerar uma resposta ou executar uma tarefa." },
  { term: "UX", category: "Design", tags: ["Design", "Produto"], meaning: "Experiência do usuário: clareza, facilidade e sensação ao usar um produto." },
  { term: "UI", category: "Design", tags: ["Design", "Front-end"], meaning: "Interface do usuário: telas, botões, cores, tipografia e componentes visuais de um produto." },
  { term: "Wireframe", category: "Design", tags: ["Design", "Produto"], meaning: "Esboço simples de uma tela usado para pensar estrutura antes do visual final." },
  { term: "Protótipo", category: "Design", tags: ["Design", "Produto"], meaning: "Simulação navegável de um produto para testar ideias antes do desenvolvimento." },
  { term: "Persona", category: "Produto", tags: ["Produto", "Design"], meaning: "Perfil fictício baseado em usuários reais para orientar decisões de produto e design." },
  { term: "Backlog", category: "Produto", tags: ["Produto", "Gestão"], meaning: "Lista priorizada de tarefas, melhorias e problemas que um time pretende trabalhar." },
  { term: "Sprint", category: "Gestão", tags: ["Gestão", "Produto"], meaning: "Ciclo curto de trabalho em metodologias ágeis, geralmente com uma meta clara para o time." },
  { term: "KPI", category: "Produto", tags: ["Produto", "Dados"], meaning: "Indicador usado para medir se uma ação ou produto está chegando no resultado esperado." },
  { term: "Cloud", category: "Infra", tags: ["Infra", "Cloud"], meaning: "Servidores e serviços acessados pela internet, como AWS, Azure e Google Cloud." },
  { term: "Container", category: "DevOps", tags: ["DevOps", "Cloud"], meaning: "Pacote que leva uma aplicação e suas dependências para rodar de forma consistente em ambientes diferentes." },
  { term: "CI/CD", category: "DevOps", tags: ["DevOps", "Ferramentas"], meaning: "Práticas para testar, integrar e publicar código com mais frequência e menos trabalho manual." },
  { term: "Firewall", category: "Segurança", tags: ["Segurança", "Infra"], meaning: "Barreira que controla o tráfego de rede permitido ou bloqueado para proteger sistemas." },
  { term: "Phishing", category: "Segurança", tags: ["Segurança", "Carreira"], meaning: "Golpe que tenta enganar pessoas para roubar senhas, dados ou acesso a contas." },
  { term: "Bug", category: "QA", tags: ["QA", "Programação"], meaning: "Erro ou comportamento inesperado em um software." },
  { term: "Teste de regressão", category: "QA", tags: ["QA", "Programação"], meaning: "Teste feito para garantir que uma mudança nova não quebrou algo que já funcionava." },
  { term: "MVP", category: "Produto", tags: ["Produto", "Carreira"], meaning: "Versão mínima de um produto criada para validar uma ideia com usuários reais." },
  { term: "Portfólio", category: "Carreira", tags: ["Carreira", "Portfólio"], meaning: "Coleção de projetos e evidências que mostram o que você sabe fazer." },
  { term: "Networking", category: "Carreira", tags: ["Carreira", "Comunidade"], meaning: "Construção de relações profissionais para trocar conhecimento, oportunidades e apoio." },
  { term: "Algoritmo", category: "Programação", tags: ["Programação", "Lógica"], meaning: "Sequência de passos para resolver um problema ou executar uma tarefa." },
  { term: "Variável", category: "Programação", tags: ["Programação", "Lógica"], meaning: "Espaço com nome usado para guardar um valor que pode ser usado pelo código." },
  { term: "Função", category: "Programação", tags: ["Programação", "Lógica"], meaning: "Bloco de código reutilizável que executa uma ação ou devolve um resultado." },
  { term: "Loop", category: "Programação", tags: ["Programação", "Lógica"], meaning: "Estrutura que repete uma instrução enquanto uma condição for verdadeira ou para cada item de uma lista." },
  { term: "Condicional", category: "Programação", tags: ["Programação", "Lógica"], meaning: "Estrutura como if/else usada para tomar decisões dentro do código." },
  { term: "Array", category: "Programação", tags: ["Programação", "Front-end"], meaning: "Lista ordenada de valores que pode guardar textos, números, objetos ou outros dados." },
  { term: "Objeto", category: "Programação", tags: ["Programação", "Front-end"], meaning: "Estrutura que agrupa dados em pares de chave e valor, como nome, idade e email." },
  { term: "TypeScript", category: "Programação", tags: ["Programação", "Front-end", "Back-end"], meaning: "Versão do JavaScript com tipos, ajudando a encontrar erros antes de rodar o código." },
  { term: "Node.js", category: "Back-end", tags: ["Back-end", "Programação"], meaning: "Ambiente que permite executar JavaScript fora do navegador, muito usado para criar APIs." },
  { term: "NPM", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Gerenciador de pacotes do ecossistema JavaScript para instalar bibliotecas e scripts." },
  { term: "PNPM", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Gerenciador de pacotes JavaScript rápido e econômico no uso de espaço em disco." },
  { term: "Vite", category: "Front-end", tags: ["Front-end", "Ferramentas"], meaning: "Ferramenta moderna para criar, desenvolver e empacotar aplicações front-end." },
  { term: "SPA", category: "Front-end", tags: ["Front-end", "Programação"], meaning: "Aplicação de página única que troca telas sem recarregar o site inteiro." },
  { term: "SSR", category: "Front-end", tags: ["Front-end", "Performance"], meaning: "Renderização no servidor, técnica em que a página chega pronta ou quase pronta ao navegador." },
  { term: "SEO", category: "Marketing Tech", tags: ["Front-end", "Carreira"], meaning: "Conjunto de práticas para melhorar a visibilidade de páginas em buscadores como Google." },
  { term: "Acessibilidade", category: "Design", tags: ["Design", "Front-end"], meaning: "Prática de criar produtos que também funcionem bem para pessoas com diferentes necessidades." },
  { term: "Semântica", category: "Front-end", tags: ["Front-end", "Acessibilidade"], meaning: "Uso de elementos HTML com significado correto para melhorar leitura, SEO e acessibilidade." },
  { term: "Flexbox", category: "Front-end", tags: ["Front-end", "Design"], meaning: "Modelo de layout CSS usado para alinhar e distribuir elementos em uma direção." },
  { term: "Grid", category: "Front-end", tags: ["Front-end", "Design"], meaning: "Modelo de layout CSS para criar estruturas em linhas e colunas." },
  { term: "Componente", category: "Front-end", tags: ["Front-end", "Design System"], meaning: "Parte reutilizável de uma interface, como botão, card, menu ou modal." },
  { term: "Props", category: "Front-end", tags: ["Front-end", "React"], meaning: "Dados enviados para um componente React para personalizar o que ele mostra ou faz." },
  { term: "State", category: "Front-end", tags: ["Front-end", "React"], meaning: "Dados internos de um componente que mudam com interação, carregamento ou lógica." },
  { term: "Hook", category: "Front-end", tags: ["Front-end", "React"], meaning: "Função especial do React usada para estado, efeitos e outras capacidades em componentes." },
  { term: "Roteamento", category: "Front-end", tags: ["Front-end", "Programação"], meaning: "Organização das URLs e telas de uma aplicação, como /perfil ou /cursos." },
  { term: "Formulário", category: "Front-end", tags: ["Front-end", "UX"], meaning: "Interface para coletar informações da pessoa usuária, como cadastro, login ou busca." },
  { term: "Validação", category: "Programação", tags: ["Front-end", "Back-end", "QA"], meaning: "Checagem para garantir que dados enviados estão corretos, completos e seguros." },
  { term: "CRUD", category: "Back-end", tags: ["Back-end", "Dados"], meaning: "Operações básicas de criar, ler, atualizar e deletar dados." },
  { term: "HTTP", category: "Back-end", tags: ["Back-end", "API"], meaning: "Protocolo usado pela web para comunicação entre navegador, apps, servidores e APIs." },
  { term: "HTTPS", category: "Segurança", tags: ["Segurança", "Back-end"], meaning: "Versão segura do HTTP, com criptografia para proteger dados em trânsito." },
  { term: "Request", category: "Back-end", tags: ["Back-end", "API"], meaning: "Pedido enviado por um cliente, como navegador ou app, para um servidor." },
  { term: "Response", category: "Back-end", tags: ["Back-end", "API"], meaning: "Resposta que o servidor devolve depois de receber um request." },
  { term: "Status code", category: "Back-end", tags: ["Back-end", "API"], meaning: "Código numérico que indica o resultado de uma requisição, como 200, 404 ou 500." },
  { term: "Middleware", category: "Back-end", tags: ["Back-end", "Segurança"], meaning: "Camada de código que roda entre a requisição e a resposta para validar, registrar ou modificar algo." },
  { term: "Servidor", category: "Infra", tags: ["Infra", "Back-end"], meaning: "Computador ou serviço que recebe pedidos e entrega respostas, arquivos, páginas ou dados." },
  { term: "Cliente", category: "Programação", tags: ["Front-end", "Back-end"], meaning: "Parte que consome um serviço, como navegador, app mobile ou outro sistema." },
  { term: "Cache", category: "Performance", tags: ["Performance", "Back-end", "Front-end"], meaning: "Armazenamento temporário usado para evitar trabalho repetido e deixar respostas mais rápidas." },
  { term: "Cookie", category: "Web", tags: ["Front-end", "Segurança"], meaning: "Pequeno dado salvo no navegador, usado para sessão, preferências ou rastreamento." },
  { term: "Token", category: "Segurança", tags: ["Segurança", "Back-end"], meaning: "Código usado para representar acesso, sessão ou permissão entre sistemas." },
  { term: "JWT", category: "Segurança", tags: ["Segurança", "Back-end"], meaning: "Tipo de token que carrega informações assinadas para autenticação e autorização." },
  { term: "OAuth", category: "Segurança", tags: ["Segurança", "Back-end"], meaning: "Padrão usado para login e autorização com provedores como Google, GitHub ou Microsoft." },
  { term: "Hash", category: "Segurança", tags: ["Segurança", "Back-end"], meaning: "Resultado de transformar um dado em uma sequência fixa, muito usado para proteger senhas." },
  { term: "Criptografia", category: "Segurança", tags: ["Segurança", "Infra"], meaning: "Técnica para proteger informações tornando os dados ilegíveis sem a chave correta." },
  { term: "Vulnerabilidade", category: "Segurança", tags: ["Segurança", "QA"], meaning: "Falha que pode ser explorada para comprometer dados, sistemas ou contas." },
  { term: "Pentest", category: "Segurança", tags: ["Segurança", "Carreira"], meaning: "Teste de invasão autorizado para encontrar vulnerabilidades antes de atacantes reais." },
  { term: "SOC", category: "Segurança", tags: ["Segurança", "Carreira"], meaning: "Centro de operações de segurança que monitora alertas, ameaças e incidentes." },
  { term: "Malware", category: "Segurança", tags: ["Segurança"], meaning: "Software malicioso criado para roubar dados, causar danos ou obter acesso indevido." },
  { term: "Ransomware", category: "Segurança", tags: ["Segurança"], meaning: "Ataque que sequestra dados ou sistemas e cobra resgate para liberar o acesso." },
  { term: "LGPD", category: "Segurança", tags: ["Segurança", "Produto"], meaning: "Lei brasileira que define regras para coleta, uso, proteção e descarte de dados pessoais." },
  { term: "Tabela", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Estrutura de banco relacional organizada em linhas e colunas." },
  { term: "Registro", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Linha de uma tabela que representa uma entidade ou evento específico." },
  { term: "Chave primária", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Campo que identifica de forma única um registro em uma tabela." },
  { term: "Chave estrangeira", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Campo que conecta uma tabela a outra dentro de um banco relacional." },
  { term: "JOIN", category: "Dados", tags: ["Dados", "SQL"], meaning: "Operação SQL usada para combinar dados de duas ou mais tabelas." },
  { term: "NoSQL", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Família de bancos de dados que não seguem o modelo relacional tradicional." },
  { term: "ETL", category: "Dados", tags: ["Dados", "Cloud"], meaning: "Processo de extrair, transformar e carregar dados entre sistemas." },
  { term: "Data Lake", category: "Dados", tags: ["Dados", "Cloud"], meaning: "Repositório que guarda grandes volumes de dados em formatos variados para análises futuras." },
  { term: "Data Warehouse", category: "Dados", tags: ["Dados", "BI"], meaning: "Banco organizado para relatórios, métricas e análises de negócio." },
  { term: "BI", category: "Dados", tags: ["Dados", "Produto"], meaning: "Business Intelligence: uso de dados para criar relatórios, dashboards e apoiar decisões." },
  { term: "Pandas", category: "Dados", tags: ["Dados", "Python"], meaning: "Biblioteca Python usada para manipular, limpar e analisar dados em tabelas." },
  { term: "Notebook", category: "Dados", tags: ["Dados", "Ferramentas"], meaning: "Ambiente interativo para escrever código, textos, gráficos e análises no mesmo arquivo." },
  { term: "Métrica", category: "Produto", tags: ["Produto", "Dados"], meaning: "Medida acompanhada para entender comportamento, resultado ou qualidade de algo." },
  { term: "Correlação", category: "Dados", tags: ["Dados", "Estatística"], meaning: "Relação estatística entre duas variáveis, sem necessariamente indicar causa." },
  { term: "Média", category: "Dados", tags: ["Dados", "Estatística"], meaning: "Soma dos valores dividida pela quantidade de valores." },
  { term: "Mediana", category: "Dados", tags: ["Dados", "Estatística"], meaning: "Valor central de um conjunto ordenado, útil quando existem valores muito extremos." },
  { term: "Overfitting", category: "IA", tags: ["IA", "Dados"], meaning: "Quando um modelo aprende demais os dados de treino e vai mal em dados novos." },
  { term: "Treinamento", category: "IA", tags: ["IA", "Dados"], meaning: "Processo de ensinar um modelo usando dados e exemplos." },
  { term: "Inferência", category: "IA", tags: ["IA", "Dados"], meaning: "Uso de um modelo já treinado para gerar previsão, resposta ou classificação." },
  { term: "Rede neural", category: "IA", tags: ["IA", "Dados"], meaning: "Modelo inspirado em conexões de neurônios, usado em tarefas como imagem, texto e voz." },
  { term: "Deep Learning", category: "IA", tags: ["IA", "Dados"], meaning: "Área de machine learning baseada em redes neurais com muitas camadas." },
  { term: "LLM", category: "IA", tags: ["IA", "Produtividade"], meaning: "Modelo de linguagem grande treinado para entender e gerar texto, código e respostas." },
  { term: "Fine-tuning", category: "IA", tags: ["IA", "Dados"], meaning: "Ajuste de um modelo já treinado com dados específicos para melhorar uma tarefa." },
  { term: "Embedding", category: "IA", tags: ["IA", "Dados"], meaning: "Representação numérica de texto, imagem ou dado para comparação e busca semântica." },
  { term: "RAG", category: "IA", tags: ["IA", "Dados"], meaning: "Técnica que combina busca em documentos com IA para gerar respostas mais contextualizadas." },
  { term: "Alucinação", category: "IA", tags: ["IA", "Produtividade"], meaning: "Quando uma IA gera uma resposta convincente, mas incorreta ou inventada." },
  { term: "Docker", category: "DevOps", tags: ["DevOps", "Cloud"], meaning: "Ferramenta para criar e executar containers de aplicações." },
  { term: "Kubernetes", category: "DevOps", tags: ["DevOps", "Cloud"], meaning: "Plataforma para orquestrar containers em ambientes com muitas aplicações e servidores." },
  { term: "Pipeline", category: "DevOps", tags: ["DevOps", "Ferramentas"], meaning: "Sequência automatizada de etapas, como instalar, testar, buildar e publicar um projeto." },
  { term: "Build", category: "DevOps", tags: ["DevOps", "Front-end"], meaning: "Processo de preparar o código para produção, gerando arquivos otimizados." },
  { term: "Ambiente de produção", category: "DevOps", tags: ["DevOps", "Cloud"], meaning: "Ambiente real usado por pessoas usuárias finais." },
  { term: "Ambiente de homologação", category: "DevOps", tags: ["DevOps", "QA"], meaning: "Ambiente parecido com produção usado para testar antes de liberar mudanças." },
  { term: "Log", category: "DevOps", tags: ["DevOps", "Back-end"], meaning: "Registro de eventos do sistema usado para investigar erros e comportamento." },
  { term: "Monitoramento", category: "DevOps", tags: ["DevOps", "Cloud"], meaning: "Acompanhamento de métricas, erros e saúde de sistemas em tempo real." },
  { term: "Observabilidade", category: "DevOps", tags: ["DevOps", "Performance"], meaning: "Capacidade de entender o que acontece dentro de um sistema por logs, métricas e traces." },
  { term: "SRE", category: "DevOps", tags: ["DevOps", "Carreira"], meaning: "Site Reliability Engineering: área focada em confiabilidade, automação e operação de sistemas." },
  { term: "IaC", category: "DevOps", tags: ["DevOps", "Cloud"], meaning: "Infraestrutura como código, prática de configurar recursos de nuvem usando arquivos versionados." },
  { term: "Terraform", category: "DevOps", tags: ["DevOps", "Cloud"], meaning: "Ferramenta usada para criar e gerenciar infraestrutura como código." },
  { term: "Serverless", category: "Cloud", tags: ["Cloud", "Back-end"], meaning: "Modelo em que a nuvem gerencia servidores e a equipe foca mais no código da função ou serviço." },
  { term: "AWS", category: "Cloud", tags: ["Cloud", "Infra"], meaning: "Amazon Web Services, uma das maiores plataformas de computação em nuvem." },
  { term: "Azure", category: "Cloud", tags: ["Cloud", "Infra"], meaning: "Plataforma de computação em nuvem da Microsoft." },
  { term: "GCP", category: "Cloud", tags: ["Cloud", "Infra"], meaning: "Google Cloud Platform, plataforma de computação em nuvem do Google." },
  { term: "DNS", category: "Infra", tags: ["Infra", "Web"], meaning: "Sistema que traduz nomes de domínio, como site.com, para endereços usados por servidores." },
  { term: "Domínio", category: "Web", tags: ["Web", "Carreira"], meaning: "Nome usado para acessar um site, como exemplo.com.br." },
  { term: "Hospedagem", category: "Web", tags: ["Web", "Cloud"], meaning: "Serviço que mantém um site ou aplicação disponível na internet." },
  { term: "Latência", category: "Performance", tags: ["Performance", "Infra"], meaning: "Tempo de atraso entre uma ação e a resposta do sistema." },
  { term: "Escalabilidade", category: "Arquitetura", tags: ["Arquitetura", "Cloud"], meaning: "Capacidade de um sistema crescer para atender mais acessos, dados ou usuários." },
  { term: "Arquitetura", category: "Arquitetura", tags: ["Arquitetura", "Back-end"], meaning: "Forma como as partes de um sistema são organizadas e se comunicam." },
  { term: "Monolito", category: "Arquitetura", tags: ["Arquitetura", "Back-end"], meaning: "Aplicação em que várias partes do sistema ficam em um único projeto ou deploy." },
  { term: "Microsserviços", category: "Arquitetura", tags: ["Arquitetura", "Back-end"], meaning: "Abordagem em que o sistema é dividido em serviços menores e independentes." },
  { term: "Fila", category: "Arquitetura", tags: ["Arquitetura", "Back-end"], meaning: "Mecanismo para organizar tarefas assíncronas, evitando sobrecarregar o sistema." },
  { term: "WebSocket", category: "Back-end", tags: ["Back-end", "Front-end"], meaning: "Tecnologia para comunicação em tempo real entre cliente e servidor." },
  { term: "Teste unitário", category: "QA", tags: ["QA", "Programação"], meaning: "Teste focado em uma função, componente ou pequena parte isolada do código." },
  { term: "Teste de integração", category: "QA", tags: ["QA", "Back-end"], meaning: "Teste que verifica se diferentes partes do sistema funcionam bem juntas." },
  { term: "Teste E2E", category: "QA", tags: ["QA", "Front-end"], meaning: "Teste que simula o caminho completo da pessoa usuária, do começo ao fim." },
  { term: "Teste manual", category: "QA", tags: ["QA", "Carreira"], meaning: "Teste executado por uma pessoa seguindo cenários, critérios e observações." },
  { term: "Automação de testes", category: "QA", tags: ["QA", "Programação"], meaning: "Uso de código ou ferramentas para repetir testes automaticamente." },
  { term: "Caso de teste", category: "QA", tags: ["QA", "Produto"], meaning: "Descrição de passos, dados e resultado esperado para validar uma funcionalidade." },
  { term: "Critério de aceite", category: "Produto", tags: ["Produto", "QA"], meaning: "Condição que precisa ser verdadeira para uma tarefa ser considerada concluída." },
  { term: "Smoke test", category: "QA", tags: ["QA", "DevOps"], meaning: "Teste rápido para confirmar que as partes mais importantes do sistema ainda funcionam." },
  { term: "Design System", category: "Design", tags: ["Design", "Front-end"], meaning: "Conjunto de padrões, componentes e regras visuais para manter consistência em produtos." },
  { term: "Auto-layout", category: "Design", tags: ["Design", "Ferramentas"], meaning: "Recurso do Figma para criar layouts flexíveis com espaçamento e alinhamento automáticos." },
  { term: "Jornada do usuário", category: "Design", tags: ["Design", "Produto"], meaning: "Sequência de passos que uma pessoa percorre para alcançar um objetivo no produto." },
  { term: "Pesquisa com usuários", category: "Design", tags: ["Design", "Produto"], meaning: "Métodos para entender necessidades, dores e comportamentos de pessoas usuárias." },
  { term: "Usabilidade", category: "Design", tags: ["Design", "UX"], meaning: "Qualidade de um produto ser fácil, claro e eficiente de usar." },
  { term: "Heurísticas", category: "Design", tags: ["Design", "UX"], meaning: "Princípios usados para avaliar se uma interface é clara, consistente e fácil de usar." },
  { term: "Benchmark", category: "Produto", tags: ["Produto", "Carreira"], meaning: "Comparação com produtos, empresas ou referências para aprender boas práticas e oportunidades." },
  { term: "Discovery", category: "Produto", tags: ["Produto", "Design"], meaning: "Fase de investigação para entender problema, público, contexto e possíveis soluções." },
  { term: "Delivery", category: "Produto", tags: ["Produto", "Gestão"], meaning: "Fase de construção e entrega da solução planejada." },
  { term: "Stakeholder", category: "Produto", tags: ["Produto", "Gestão"], meaning: "Pessoa ou grupo interessado no resultado de um projeto ou produto." },
  { term: "Roadmap", category: "Produto", tags: ["Produto", "Carreira"], meaning: "Plano visual ou lista priorizada que mostra a direção e próximas entregas." },
  { term: "Kanban", category: "Gestão", tags: ["Gestão", "Produto"], meaning: "Método visual de organização do trabalho com colunas como a fazer, fazendo e feito." },
  { term: "Scrum", category: "Gestão", tags: ["Gestão", "Produto"], meaning: "Framework ágil com papéis, eventos e ciclos curtos para organizar entregas." },
  { term: "Daily", category: "Gestão", tags: ["Gestão", "Produto"], meaning: "Reunião rápida do time para alinhar andamento, foco e bloqueios." },
  { term: "Retrospectiva", category: "Gestão", tags: ["Gestão", "Produto"], meaning: "Reunião para revisar o que funcionou, o que melhorar e quais ações tomar no próximo ciclo." },
  { term: "Product Owner", category: "Produto", tags: ["Produto", "Carreira"], meaning: "Pessoa responsável por priorizar o backlog e maximizar valor entregue pelo time." },
  { term: "Product Manager", category: "Produto", tags: ["Produto", "Carreira"], meaning: "Pessoa que conecta usuário, negócio e tecnologia para direcionar a evolução do produto." },
  { term: "Issue", category: "Ferramentas", tags: ["Ferramentas", "Gestão"], meaning: "Tarefa, bug ou solicitação registrada em ferramentas como GitHub, Jira ou Linear." },
  { term: "Pull Request", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Pedido de revisão para integrar mudanças de código a uma branch principal." },
  { term: "Branch", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Linha paralela de desenvolvimento usada para trabalhar sem mexer diretamente na versão principal." },
  { term: "Commit", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Registro de uma mudança no histórico do Git." },
  { term: "Merge", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Ação de juntar mudanças de uma branch em outra." },
  { term: "Conflito de merge", category: "Ferramentas", tags: ["Ferramentas", "Programação"], meaning: "Situação em que o Git precisa de ajuda para decidir entre mudanças diferentes no mesmo trecho." },
  { term: "README", category: "Portfólio", tags: ["Portfólio", "Ferramentas"], meaning: "Arquivo que explica objetivo, instalação, uso, tecnologias e aprendizados de um projeto." },
  { term: "Open Source", category: "Carreira", tags: ["Carreira", "Comunidade"], meaning: "Projeto com código aberto para estudo, uso e contribuição da comunidade." },
  { term: "Freelancer", category: "Carreira", tags: ["Carreira"], meaning: "Profissional autônomo que trabalha por projeto, demanda ou contrato." },
  { term: "Estágio", category: "Carreira", tags: ["Carreira"], meaning: "Oportunidade de aprendizado prático para estudantes entrarem no mercado." },
  { term: "Júnior", category: "Carreira", tags: ["Carreira"], meaning: "Nível inicial de carreira, com autonomia em crescimento e necessidade de acompanhamento." },
  { term: "Hard skills", category: "Carreira", tags: ["Carreira"], meaning: "Habilidades técnicas, como programar, testar, analisar dados ou usar ferramentas." },
  { term: "Soft skills", category: "Carreira", tags: ["Carreira"], meaning: "Habilidades comportamentais, como comunicação, organização, colaboração e adaptabilidade." },
  { term: "Mentoria", category: "Carreira", tags: ["Carreira", "Comunidade"], meaning: "Acompanhamento de alguém mais experiente para orientar próximos passos e decisões." },
  { term: "Currículo", category: "Carreira", tags: ["Carreira"], meaning: "Documento que resume formação, experiências, projetos, habilidades e contatos profissionais." },
  { term: "LinkedIn", category: "Carreira", tags: ["Carreira", "Portfólio"], meaning: "Rede profissional usada para networking, vagas, conteúdo e posicionamento de carreira." },
  { term: "React Native", category: "Mobile", tags: ["Mobile", "Front-end"], meaning: "Framework para criar aplicativos mobile usando JavaScript e React." },
  { term: "Flutter", category: "Mobile", tags: ["Mobile", "Front-end"], meaning: "Framework do Google para criar apps mobile e multiplataforma usando Dart." },
  { term: "APK", category: "Mobile", tags: ["Mobile"], meaning: "Arquivo usado para instalar aplicativos Android." },
  { term: "App Store", category: "Mobile", tags: ["Mobile", "Carreira"], meaning: "Loja oficial da Apple para publicar e baixar apps de iPhone e iPad." },
  { term: "Play Store", category: "Mobile", tags: ["Mobile", "Carreira"], meaning: "Loja oficial do Google para publicar e baixar apps Android." },
  { term: "Expo", category: "Mobile", tags: ["Mobile", "Ferramentas"], meaning: "Conjunto de ferramentas que facilita criar, testar e publicar apps React Native." },
  { term: "Firebase", category: "Mobile", tags: ["Mobile", "Back-end", "Cloud"], meaning: "Plataforma do Google com autenticação, banco, hospedagem e recursos para apps." },
  { term: "GraphQL", category: "Back-end", tags: ["Back-end", "API"], meaning: "Linguagem de consulta para APIs onde a cliente pede só os campos que precisa em uma única requisição." },
  { term: "gRPC", category: "Back-end", tags: ["Back-end", "API"], meaning: "Framework RPC que usa protobuf e HTTP/2 para comunicação rápida e contratos fortes entre serviços." },
  { term: "ORM", category: "Back-end", tags: ["Back-end", "Dados"], meaning: "Camada que mapeia tabelas do banco para objetos no código, reduzindo SQL manual." },
  { term: "Migração", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Script versionado que altera estrutura do banco de forma controlada e repetível." },
  { term: "Índice (banco)", category: "Dados", tags: ["Dados", "Performance"], meaning: "Estrutura que acelera buscas em colunas, com trade-off de espaço e custo em escritas." },
  { term: "Transação", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Grupo de operações que ou todas confirmam ou todas desfazem, mantendo consistência." },
  { term: "Deadlock", category: "Dados", tags: ["Dados", "Back-end"], meaning: "Situação em que transações ficam esperando uma pela outra indefinidamente." },
  { term: "Normalização", category: "Dados", tags: ["Dados", "SQL"], meaning: "Organizar dados para reduzir redundância e inconsistência em bancos relacionais." },
  { term: "Denormalização", category: "Dados", tags: ["Dados", "Performance"], meaning: "Duplicar ou juntar dados de propósito para acelerar leituras em certos casos." },
  { term: "Mensageria", category: "Arquitetura", tags: ["Arquitetura", "Back-end"], meaning: "Uso de filas ou brokers para processar trabalhos fora do fluxo principal da requisição." },
  { term: "Pub/Sub", category: "Arquitetura", tags: ["Arquitetura", "Cloud"], meaning: "Modelo em que publicadores enviam eventos e assinantes recebem sem acoplamento direto." },
  { term: "Idempotência", category: "Back-end", tags: ["Back-end", "API"], meaning: "Propriedade em que repetir a mesma operação segura não muda o resultado além da primeira vez." },
  { term: "Rate limit", category: "Segurança", tags: ["Segurança", "API"], meaning: "Limite de requisições por tempo para proteger serviços contra abuso ou sobrecarga." },
  { term: "CORS", category: "Web", tags: ["Web", "Back-end", "Front-end"], meaning: "Mecanismo do navegador que controla se um site pode chamar API de outro domínio." },
  { term: "CSRF", category: "Segurança", tags: ["Segurança", "Web"], meaning: "Ataque que engana o navegador a enviar ação autenticada sem intenção da pessoa usuária." },
  { term: "XSS", category: "Segurança", tags: ["Segurança", "Web"], meaning: "Injeção de script em páginas para roubar sessão ou alterar o que outros veem." },
  { term: "SQL injection", category: "Segurança", tags: ["Segurança", "Dados"], meaning: "Ataque que insere SQL malicioso em entradas para ler ou alterar dados indevidos." },
  { term: "DDoS", category: "Segurança", tags: ["Segurança", "Infra"], meaning: "Volume massivo de tráfego para derrubar ou degradar um serviço online." },
  { term: "VPN", category: "Infra", tags: ["Infra", "Segurança"], meaning: "Túnel criptografado que protege tráfego, comum em acesso remoto corporativo." },
  { term: "CDN", category: "Infra", tags: ["Infra", "Performance"], meaning: "Rede que entrega arquivos estáticos de servidores próximos da pessoa usuária." },
  { term: "Load balancer", category: "Infra", tags: ["Infra", "Cloud"], meaning: "Distribui requisições entre vários servidores para escala e resiliência." },
  { term: "Reverse proxy", category: "Infra", tags: ["Infra", "Back-end"], meaning: "Servidor na frente dos apps que encamina tráfego, pode cachear, TLS e regras de rota." },
  { term: "IP", category: "Redes", tags: ["Infra", "Web"], meaning: "Endereço numérico que identifica um dispositivo em uma rede." },
  { term: "TCP/IP", category: "Redes", tags: ["Infra", "Back-end"], meaning: "Conjunto de protocolos que define como dados trafegam na internet de forma confiável." },
  { term: "UDP", category: "Redes", tags: ["Infra", "Back-end"], meaning: "Protocolo mais simples e sem garantia de ordem, usado em streaming e jogos em tempo real." },
  { term: "SSH", category: "Ferramentas", tags: ["Ferramentas", "DevOps"], meaning: "Protocolo seguro para acessar terminal de servidores remotos." },
  { term: "YAML", category: "Ferramentas", tags: ["Ferramentas", "DevOps"], meaning: "Formato de arquivo legível por humanos para configs, pipelines e infraestrutura." },
  { term: "Regex", category: "Programação", tags: ["Programação", "Dados"], meaning: "Padrão para buscar ou validar texto com regras compactas." },
  { term: "Timezone", category: "Programação", tags: ["Programação", "Back-end"], meaning: "Fuso horário que afeta datas em agendamentos, logs e notificações." },
  { term: "Unicode", category: "Programação", tags: ["Programação", "Web"], meaning: "Padrão que representa caracteres de praticamente todos os sistemas de escrita." },
  { term: "UTF-8", category: "Programação", tags: ["Programação", "Web"], meaning: "Codificação comum que armazena Unicode de forma compacta e compatível com ASCII." },
  { term: "Semáforo", category: "Programação", tags: ["Programação", "Back-end"], meaning: "Primitiva de concorrência que limita quantas tarefas acessam um recurso ao mesmo tempo." },
  { term: "Dead letter queue", category: "Arquitetura", tags: ["Arquitetura", "Cloud"], meaning: "Fila para mensagens que falharam após tentativas, para análise e reprocessamento." },
  { term: "Feature flag", category: "Produto", tags: ["Produto", "DevOps"], meaning: "Interruptor remoto que liga ou desliga funcionalidade sem novo deploy." },
  { term: "A/B test", category: "Produto", tags: ["Produto", "Dados"], meaning: "Experimento que compara duas versões com tráfego dividido para medir resultado." },
  { term: "OKR", category: "Gestão", tags: ["Gestão", "Produto"], meaning: "Metodologia de objetivos ambiciosos e resultados mensuráveis em ciclos." },
  { term: "SLA", category: "Gestão", tags: ["Gestão", "DevOps"], meaning: "Acordo formal sobre disponibilidade, tempo de resposta ou suporte esperado." },
  { term: "SLO", category: "DevOps", tags: ["DevOps", "Gestão"], meaning: "Meta interna de confiabilidade, como tempo disponível ou latência aceitável." },
  { term: "Incidente", category: "DevOps", tags: ["DevOps", "Carreira"], meaning: "Evento que prejudica usuários ou serviço e exige resposta coordenada." },
  { term: "Postmortem", category: "DevOps", tags: ["DevOps", "Gestão"], meaning: "Documento após incidente com causa, impacto e ações para não repetir." },
  { term: "TDD", category: "QA", tags: ["QA", "Programação"], meaning: "Prática de escrever teste antes do código que o satisfaz." },
  { term: "BDD", category: "QA", tags: ["QA", "Produto"], meaning: "Abordagem que descreve comportamento em linguagem próxima ao negócio antes de implementar." },
  { term: "Mock", category: "QA", tags: ["QA", "Programação"], meaning: "Objeto ou serviço falso que simula dependências em testes." },
  { term: "Stub", category: "QA", tags: ["QA", "Programação"], meaning: "Implementação mínima que devolve respostas fixas para isolar o código sob teste." },
  { term: "Faker / dado sintético", category: "Dados", tags: ["Dados", "QA"], meaning: "Dados inventados mas realistas para testes sem vazar informação real." },
  { term: "Golden file", category: "QA", tags: ["QA", "Programação"], meaning: "Arquivo de referência comparado com saída atual para detectar mudanças inesperadas." },
  { term: "Flaky test", category: "QA", tags: ["QA", "Programação"], meaning: "Teste que às vezes passa e às vezes falha sem mudança clara no código." },
  { term: "Snapshot", category: "QA", tags: ["QA", "Front-end"], meaning: "Arquivo serializado do output esperado de um componente para comparação automática." },
  { term: "Lighthouse", category: "Performance", tags: ["Performance", "Front-end"], meaning: "Ferramenta do Chrome que audita performance, acessibilidade e SEO de páginas." },
  { term: "Core Web Vitals", category: "Performance", tags: ["Performance", "SEO"], meaning: "Métricas do Google sobre carregamento, interatividade e estabilidade visual." },
  { term: "Bundle", category: "Front-end", tags: ["Front-end", "DevOps"], meaning: "Arquivo empacotado com JavaScript/CSS para enviar ao navegador." },
  { term: "Tree shaking", category: "Front-end", tags: ["Front-end", "Performance"], meaning: "Remoção de código não usado no build final." },
  { term: "Code splitting", category: "Front-end", tags: ["Front-end", "Performance"], meaning: "Dividir o bundle em partes carregadas sob demanda para abrir a página mais rápido." },
  { term: "Hydration", category: "Front-end", tags: ["Front-end", "Performance"], meaning: "No SSR, processo em que o JS do cliente 'ativa' interatividade no HTML já entregue." },
  { term: "WebAssembly", category: "Programação", tags: ["Programação", "Performance"], meaning: "Formato binário executável no navegador com desempenho próximo ao nativo." },
  { term: "Canvas", category: "Front-end", tags: ["Front-end", "Games"], meaning: "Elemento HTML para desenhar gráficos 2D via JavaScript." },
  { term: "WebGL", category: "Front-end", tags: ["Front-end", "Games"], meaning: "API para gráficos 3D acelerados por GPU no navegador." },
  { term: "Game loop", category: "Games", tags: ["Games", "Programação"], meaning: "Ciclo de atualizar estado e desenhar quadros em jogos e simulações." },
  { term: "Shader", category: "Games", tags: ["Games", "Front-end"], meaning: "Programa que roda na GPU para efeitos visuais em 2D/3D." },
  { term: "GDPR", category: "Segurança", tags: ["Segurança", "Produto"], meaning: "Regulamento europeu sobre dados pessoais e direitos dos titulares." },
  { term: "Consentimento", category: "Produto", tags: ["Produto", "Segurança"], meaning: "Permissão explícita e informada para usar dados ou cookies, exigida em várias leis." },
  { term: "PII", category: "Dados", tags: ["Dados", "Segurança"], meaning: "Informações que identificam uma pessoa direta ou indiretamente." },
  { term: "Anonimização", category: "Dados", tags: ["Dados", "Segurança"], meaning: "Remover ou alterar dados para não permitir identificar a pessoa." },
  { term: "Blockchain", category: "Web3", tags: ["Web3", "Dados"], meaning: "Cadeia de blocos imutável usada em registros distribuídos e criptomoedas." },
  { term: "Smart contract", category: "Web3", tags: ["Web3", "Back-end"], meaning: "Programa que roda em blockchain quando condições são atendidas." },
  { term: "NFT", category: "Web3", tags: ["Web3", "Design"], meaning: "Token não fungível que representa posse única de ativo digital em alguns blockchains." },
  { term: "Ledger", category: "Dados", tags: ["Dados", "Finanças"], meaning: "Registro cronológico de transações ou eventos contábeis." },
  { term: "IoT", category: "Hardware", tags: ["Hardware", "Cloud"], meaning: "Internet das Coisas: sensores e dispositivos conectados coletando dados." },
  { term: "Firmware", category: "Hardware", tags: ["Hardware", "Programação"], meaning: "Software embarcado que controla hardware de baixo nível." },
  { term: "RTOS", category: "Hardware", tags: ["Hardware", "Programação"], meaning: "Sistema operacional de tempo real com previsibilidade de resposta." },
  { term: "CAD", category: "Hardware", tags: ["Hardware", "Design"], meaning: "Software de desenho técnico 3D usado em engenharia e prototipagem." },
  { term: "Gerber", category: "Hardware", tags: ["Hardware"], meaning: "Formato de arquivos para fabricação de placas de circuito impresso." },
  { term: "CMS", category: "Web", tags: ["Web", "Produto"], meaning: "Sistema para criar e editar conteúdo de sites sem programar tudo do zero." },
  { term: "Headless CMS", category: "Web", tags: ["Web", "Back-end"], meaning: "CMS que só entrega conteúdo via API; o front é separado." },
  { term: "Webhook", category: "Back-end", tags: ["Back-end", "API"], meaning: "URL que recebe notificação HTTP quando um sistema externo dispara um evento." },
  { term: "Cron job", category: "DevOps", tags: ["DevOps", "Back-end"], meaning: "Tarefa agendada em intervalos fixos, como backups ou relatórios." },
  { term: "GDScript", category: "Games", tags: ["Games", "Programação"], meaning: "Linguagem do motor Godot para criar jogos 2D e 3D." },
  { term: "Unity", category: "Games", tags: ["Games", "Carreira"], meaning: "Motor popular para jogos multiplataforma com editor visual." },
  { term: "Unreal Engine", category: "Games", tags: ["Games", "Carreira"], meaning: "Motor gráfico avançado comum em jogos AA/AAA e visualização 3D." },
  { term: "Sprite", category: "Games", tags: ["Games", "Design"], meaning: "Imagem 2D usada como personagem, item ou parte da cena." },
  { term: "Collider", category: "Games", tags: ["Games", "Programação"], meaning: "Volume invisível que detecta colisões entre objetos na física do jogo." },
  { term: "Ray tracing", category: "Games", tags: ["Games", "Hardware"], meaning: "Técnica que simula luz realista traçando raios, exige GPU forte." },
  { term: "Áudio sampling", category: "Áudio", tags: ["Áudio", "Dados"], meaning: "Medir amplitude do som em intervalos para digitalizar onda analógica." },
  { term: "Codec", category: "Áudio", tags: ["Áudio", "Web"], meaning: "Algoritmo que comprime e descomprime áudio ou vídeo (ex.: Opus, H.264)." },
  { term: "FFT", category: "Áudio", tags: ["Áudio", "IA"], meaning: "Transformada que converte sinal no tempo em frequências, útil em análise e ML de áudio." },
  { term: "Latência de áudio", category: "Áudio", tags: ["Áudio", "Games"], meaning: "Atraso entre captura/processamento e o som ouvido; crítica em música e jogos online." },
  { term: "Compliance", category: "Carreira", tags: ["Carreira", "Segurança"], meaning: "Conjunto de regras e auditorias que a empresa precisa seguir em setores regulados." },
  { term: "On-call", category: "DevOps", tags: ["DevOps", "Carreira"], meaning: "Plantão em que alguém do time responde a alertas fora do horário comercial." },
  { term: "Runbook", category: "DevOps", tags: ["DevOps", "Gestão"], meaning: "Passo a passo documentado para resolver incidentes ou tarefas operacionais." },
  { term: "RFC", category: "Arquitetura", tags: ["Arquitetura", "Carreira"], meaning: "Documento de proposta para mudanças grandes, com contexto, opções e decisão." },
  { term: "ADR", category: "Arquitetura", tags: ["Arquitetura", "Carreira"], meaning: "Architecture Decision Record: registro curto de por que uma decisão técnica foi tomada." },
  { term: "Diagrama C4", category: "Arquitetura", tags: ["Arquitetura", "Gestão"], meaning: "Modelo em camadas (contexto, containers, componentes, código) para explicar sistemas." },
  { term: "GD&T", category: "Hardware", tags: ["Hardware"], meaning: "Sistema de símbolos para tolerâncias geométricas em desenhos técnicos." },
  { term: "EPC", category: "IoT", tags: ["Hardware", "Redes"], meaning: "Identificador de produto eletrônico usado em RFID para rastrear itens." },
];

export const comparisonOptions = {
  faculdades: ["ADS", "Ciência da Computação", "Sistemas de Informação"],
  areas: ["Front-end", "Back-end", "Dados", "UX/UI Design"],
  cursos: ["Curso em Vídeo", "freeCodeCamp", "DIO", "Microsoft Learn"],
  plataformas: ["YouTube", "Coursera", "Alura", "DIO"],
};

export const comparisonMatrix = [
  { label: "Tempo para começar", faculdades: "Médio", areas: "Rápido", cursos: "Rápido", plataformas: "Rápido" },
  { label: "Custo inicial", faculdades: "Médio/alto", areas: "Baixo", cursos: "Baixo", plataformas: "Variável" },
  { label: "Melhor uso", faculdades: "Base e diploma", areas: "Escolha de direção", cursos: "Aprender prática", plataformas: "Catálogo contínuo" },
  { label: "Risco para iniciantes", faculdades: "Escolher sem comparar", areas: "Ficar só pesquisando", cursos: "Não praticar", plataformas: "Excesso de opções" },
];

export const QUIZ_ESTIMATED_MINUTES = 5;

export const quizQuestions = [
  {
    id: "energy",
    category: "Interesse",
    question: "Que tipo de tarefa te dá mais energia por várias horas?",
    options: [
      { label: "Criar telas, interações e ver resultado visual rápido", area: "Front-end", scores: { "Front-end": 5, "Desenvolvimento Mobile": 2, "UX/UI Design": 1 } },
      { label: "Resolver lógica, regras de negócio e estrutura de sistemas", area: "Back-end", scores: { "Back-end": 5, "DevOps": 1, "Cloud Computing": 1 } },
      { label: "Investigar dados, padrões e hipóteses antes de decidir", area: "Ciência de Dados", scores: { "Ciência de Dados": 5, "Inteligência Artificial": 3, "Produto Digital": 1 } },
      { label: "Entender pessoas, mapear jornadas e melhorar experiências", area: "UX/UI Design", scores: { "UX/UI Design": 5, "Produto Digital": 3, "Gestão de Projetos Tech": 1 } },
    ],
  },
  {
    id: "problem",
    category: "Problema",
    question: "Qual problema você teria mais vontade de resolver no dia a dia?",
    options: [
      { label: "Deixar sistemas rápidos, seguros e bem organizados", area: "Back-end", scores: { "Back-end": 5, "Cloud Computing": 2, DevOps: 2 } },
      { label: "Transformar dados confusos em decisões claras", area: "Ciência de Dados", scores: { "Ciência de Dados": 5, "Inteligência Artificial": 2, "Produto Digital": 2 } },
      { label: "Proteger pessoas e empresas contra ataques e vazamentos", area: "Cibersegurança", scores: { Cibersegurança: 5, "Cloud Computing": 2, DevOps: 1 } },
      { label: "Garantir que um produto funcione antes de chegar ao usuário", area: "QA / Testes de Software", scores: { "QA / Testes de Software": 5, "Back-end": 1, "Front-end": 1 } },
    ],
  },
  {
    id: "environment",
    category: "Ambiente",
    question: "Em qual ambiente você se imagina trabalhando melhor?",
    options: [
      { label: "Construindo interfaces em contato com design e usuário", area: "Front-end", scores: { "Front-end": 5, "UX/UI Design": 3, "Produto Digital": 1 } },
      { label: "Cuidando de servidores, nuvem, deploy e automações", area: "Cloud Computing", scores: { "Cloud Computing": 5, DevOps: 4, Cibersegurança: 1 } },
      { label: "Acompanhando prioridades, pessoas, prazos e entregas", area: "Gestão de Projetos Tech", scores: { "Gestão de Projetos Tech": 5, "Produto Digital": 4, "UX/UI Design": 1 } },
      { label: "Criando aplicativos para celular e recursos em movimento", area: "Desenvolvimento Mobile", scores: { "Desenvolvimento Mobile": 5, "Front-end": 2, "Back-end": 1 } },
    ],
  },
  {
    id: "feedback",
    category: "Motivação",
    question: "Que tipo de feedback te motiva mais?",
    options: [
      { label: "Ver alguém usando uma tela ou app que você criou", area: "Front-end", scores: { "Front-end": 4, "Desenvolvimento Mobile": 3, "UX/UI Design": 2 } },
      { label: "Ver uma automação reduzindo trabalho manual do time", area: "DevOps", scores: { DevOps: 5, "Cloud Computing": 3, "Back-end": 1 } },
      { label: "Descobrir uma falha antes que ela vire problema real", area: "QA / Testes de Software", scores: { "QA / Testes de Software": 5, Cibersegurança: 2, "Back-end": 1 } },
      { label: "Perceber que uma solução ficou simples e clara para o usuário", area: "UX/UI Design", scores: { "UX/UI Design": 5, "Produto Digital": 3, "Front-end": 1 } },
    ],
  },
  {
    id: "routine",
    category: "Rotina",
    question: "O que você gostaria de fazer no trabalho todos os dias?",
    options: [
      { label: "Construir coisas novas e ver elas aparecerem na tela rapidinho", area: "Front-end", scores: { "Front-end": 4, "Desenvolvimento Mobile": 3, "QA / Testes de Software": 1 } },
      { label: "Cuidar dos sistemas da empresa pra tudo continuar funcionando", area: "DevOps", scores: { DevOps: 5, "Cloud Computing": 4, Cibersegurança: 1 } },
      { label: "Caçar coisas suspeitas e proteger empresas de ataques", area: "Cibersegurança", scores: { Cibersegurança: 5, "Cloud Computing": 2, DevOps: 1 } },
      { label: "Falar com várias áreas pra decidir o que vai ser feito primeiro", area: "Produto Digital", scores: { "Produto Digital": 5, "Gestão de Projetos Tech": 4, "UX/UI Design": 1 } },
    ],
  },
  {
    id: "learning",
    category: "Aprendizado",
    question: "Como você prefere aprender quando está começando?",
    options: [
      { label: "Com projetos visuais curtos e muita tentativa na tela", area: "Front-end", scores: { "Front-end": 5, "Desenvolvimento Mobile": 2, "UX/UI Design": 1 } },
      { label: "Com exercícios de lógica, APIs e problemas bem definidos", area: "Back-end", scores: { "Back-end": 5, "QA / Testes de Software": 1 } },
      { label: "Com planilhas, gráficos, datasets e perguntas investigativas", area: "Ciência de Dados", scores: { "Ciência de Dados": 5, "Inteligência Artificial": 2 } },
      { label: "Com entrevistas, pesquisa, protótipos e feedback de pessoas", area: "UX/UI Design", scores: { "UX/UI Design": 5, "Produto Digital": 3 } },
    ],
  },
  {
    id: "collaboration",
    category: "Colaboração",
    question: "Com quem você mais gostaria de colaborar?",
    options: [
      { label: "Designers, pesquisadores e pessoas de produto", area: "UX/UI Design", scores: { "UX/UI Design": 5, "Produto Digital": 3, "Front-end": 1 } },
      { label: "Desenvolvedores, infraestrutura e segurança", area: "DevOps", scores: { DevOps: 5, "Cloud Computing": 3, Cibersegurança: 2 } },
      { label: "Lideranças, clientes, stakeholders e times diferentes", area: "Gestão de Projetos Tech", scores: { "Gestão de Projetos Tech": 5, "Produto Digital": 4 } },
      { label: "Analistas, cientistas, operação e áreas de negócio", area: "Ciência de Dados", scores: { "Ciência de Dados": 5, "Produto Digital": 2, "Inteligência Artificial": 1 } },
    ],
  },
  {
    id: "impact",
    category: "Impacto",
    question: "Que impacto você gostaria que seu trabalho tivesse?",
    options: [
      { label: "Ajudar usuários a navegar melhor por um produto", area: "Produto Digital", scores: { "Produto Digital": 5, "UX/UI Design": 4, "Front-end": 1 } },
      { label: "Fazer sistemas ficarem estáveis, disponíveis e escaláveis", area: "Cloud Computing", scores: { "Cloud Computing": 5, DevOps: 4, "Back-end": 1 } },
      { label: "Evitar fraudes, vazamentos e acessos indevidos", area: "Cibersegurança", scores: { Cibersegurança: 5, "Cloud Computing": 1 } },
      { label: "Criar experiências rápidas para celular", area: "Desenvolvimento Mobile", scores: { "Desenvolvimento Mobile": 5, "Front-end": 2, "UX/UI Design": 1 } },
    ],
  },
  {
    id: "first-portfolio",
    category: "Portfólio",
    question: "Qual desses primeiros projetos te empolga mais?",
    options: [
      { label: "Um site interativo bonito de mostrar pra família", area: "Front-end", scores: { "Front-end": 5, "UX/UI Design": 1 } },
      { label: "Um programa que guarda informações e responde quando alguém pede", area: "Back-end", scores: { "Back-end": 5, "Cloud Computing": 1, DevOps: 1 } },
      { label: "Uma análise mostrando o que dados de verdade revelam sobre um tema", area: "Ciência de Dados", scores: { "Ciência de Dados": 5, "Produto Digital": 1 } },
      { label: "Uma lista organizada de problemas encontrados em um app, com sugestões de conserto", area: "QA / Testes de Software", scores: { "QA / Testes de Software": 5, "Back-end": 1, "Front-end": 1 } },
    ],
  },
  {
    id: "future",
    category: "Futuro",
    question: "Qual caminho te parece mais empolgante para evoluir nos próximos anos?",
    options: [
      { label: "Criar produtos digitais usados por muita gente", area: "Produto Digital", scores: { "Produto Digital": 5, "UX/UI Design": 2, "Front-end": 1 } },
      { label: "Automatizar deploys, observabilidade e infraestrutura", area: "DevOps", scores: { DevOps: 5, "Cloud Computing": 4 } },
      { label: "Especializar-se em IA, modelos e automações inteligentes", area: "Inteligência Artificial", scores: { "Inteligência Artificial": 5, "Ciência de Dados": 4, "Back-end": 1 } },
      { label: "Liderar projetos, prazos, riscos e comunicação", area: "Gestão de Projetos Tech", scores: { "Gestão de Projetos Tech": 5, "Produto Digital": 3 } },
    ],
  },
  {
    id: "unknowns",
    category: "Raciocínio",
    question: "Quando aparece algo que você não entende, o que você costuma fazer?",
    options: [
      { label: "Testo visualmente até entender o comportamento", area: "Front-end", scores: { "Front-end": 4, "Desenvolvimento Mobile": 3, "QA / Testes de Software": 1 } },
      { label: "Quebro o problema em regras, entradas e saídas menores", area: "Back-end", scores: { "Back-end": 5, "QA / Testes de Software": 1 } },
      { label: "Procuro evidências nos dados antes de concluir", area: "Ciência de Dados", scores: { "Ciência de Dados": 5, "Inteligência Artificial": 2 } },
      { label: "Pergunto para pessoas e observo onde elas travam", area: "UX/UI Design", scores: { "UX/UI Design": 5, "Produto Digital": 3 } },
    ],
  },
  {
    id: "math-comfort",
    category: "Base técnica",
    question: "Como você se sente em relação a matemática, estatística e abstração?",
    options: [
      { label: "Quero evitar matemática pesada e começar com algo mais visual", area: "Front-end", scores: { "Front-end": 4, "UX/UI Design": 4, "QA / Testes de Software": 2 } },
      { label: "Gosto de lógica, mas prefiro matemática aplicada ao sistema", area: "Back-end", scores: { "Back-end": 5, "Cloud Computing": 2, DevOps: 1 } },
      { label: "Gosto de estatística, probabilidade e análise de padrões", area: "Ciência de Dados", scores: { "Ciência de Dados": 5, "Inteligência Artificial": 4 } },
      { label: "Gosto de abstração profunda, modelos e pesquisa", area: "Inteligência Artificial", scores: { "Inteligência Artificial": 5, "Ciência de Dados": 3, "Back-end": 1 } },
    ],
  },
  {
    id: "risk-style",
    category: "Estilo",
    question: "Qual frase combina mais com seu jeito de trabalhar?",
    options: [
      { label: "Prefiro ciclos curtos, feedback rápido e resultado visível", area: "Front-end", scores: { "Front-end": 4, "UX/UI Design": 3, "Produto Digital": 2 } },
      { label: "Prefiro construir algo robusto, mesmo que demore mais para aparecer", area: "Back-end", scores: { "Back-end": 5, "Cloud Computing": 2, DevOps: 1 } },
      { label: "Prefiro investigar com calma antes de afirmar uma resposta", area: "Ciência de Dados", scores: { "Ciência de Dados": 4, Cibersegurança: 3, "QA / Testes de Software": 2 } },
      { label: "Prefiro alinhar pessoas, riscos e decisões antes de executar", area: "Gestão de Projetos Tech", scores: { "Gestão de Projetos Tech": 5, "Produto Digital": 4 } },
    ],
  },
  {
    id: "communication",
    category: "Comunicação",
    question: "Quanto você gostaria de comunicar ideias para pessoas não técnicas?",
    options: [
      { label: "Pouco; prefiro ficar mais concentrada(o) no código", area: "Back-end", scores: { "Back-end": 4, DevOps: 3, "Cloud Computing": 2 } },
      { label: "Às vezes; quero explicar decisões técnicas quando necessário", area: "Front-end", scores: { "Front-end": 3, "QA / Testes de Software": 2, "Back-end": 2 } },
      { label: "Bastante; gosto de traduzir dados e pesquisas em decisão", area: "Ciência de Dados", scores: { "Ciência de Dados": 4, "Produto Digital": 4, "UX/UI Design": 3 } },
      { label: "Muito; quero facilitar alinhamentos e decisões do time", area: "Gestão de Projetos Tech", scores: { "Gestão de Projetos Tech": 5, "Produto Digital": 5, "UX/UI Design": 2 } },
    ],
  },
  {
    id: "debug-style",
    category: "Investigação",
    question: "Se um app que você usa começa a falhar, o que dá mais vontade de investigar?",
    options: [
      { label: "Reproduzir o que aconteceu na tela e entender o que o usuário viu", area: "Front-end", scores: { "Front-end": 4, "QA / Testes de Software": 3, "UX/UI Design": 1 } },
      { label: "Olhar onde a informação fica guardada pra achar a regra que quebrou", area: "Back-end", scores: { "Back-end": 5, DevOps: 2 } },
      { label: "Ver gráficos do sistema pra descobrir quando e por que começou", area: "DevOps", scores: { DevOps: 5, "Cloud Computing": 4 } },
      { label: "Descobrir se alguém tentou usar o sistema de um jeito errado", area: "Cibersegurança", scores: { Cibersegurança: 5, DevOps: 2, "Cloud Computing": 1 } },
    ],
  },
];

export const projectHelpVideos: Record<string, { title: string; url: string }> = {
  "landing-page-pessoal": {
    title: "Como criar uma landing page do zero",
    url: "https://www.youtube.com/results?search_query=criar+landing+page+html+css+iniciante",
  },
  "todo-list": {
    title: "To-do list com JavaScript para iniciantes",
    url: "https://www.youtube.com/results?search_query=todo+list+javascript+iniciante",
  },
  default: {
    title: "Como planejar projeto iniciante para portfólio",
    url: "https://www.youtube.com/results?search_query=projeto+iniciante+portfolio+programacao",
  },
};

export const careerInstitutes = [
  { name: "PMI", desc: "Comunidade para gestão de projetos e certificações.", url: "https://www.pmi.org" },
  { name: "SBC", desc: "Sociedade Brasileira de Computação, eventos e capítulos.", url: "https://www.sbc.org.br" },
  { name: "Interaction Design Foundation", desc: "Comunidade e estudos para UX/Product Design.", url: "https://www.interaction-design.org" },
];

export const roadmapPlans = [
  { days: "10 dias", depth: "Essencial", focus: "Entender a área, fazer um curso curto e publicar uma anotação." },
  { days: "20 dias", depth: "Prático", focus: "Criar um mini projeto guiado e registrar aprendizados no GitHub." },
  { days: "30 dias", depth: "Portfólio", focus: "Publicar projeto explicável com README, prints e post no LinkedIn." },
  { days: "60 dias", depth: "Profundidade", focus: "Repetir o ciclo, comparar ferramentas e entrar em comunidade." },
];

export interface CollegeSuggestion {
  city: string;
  name: string;
  mec: string;
  advantages: string[];
  /** Sigla do estado (UF). `null` quando a sugestão vale para qualquer UF (ex.: EAD nacional). */
  uf: string | null;
  nacional?: boolean;
}

/** 26 estados + Distrito Federal, ordenados pelo nome do estado. */
export const brazilianStates = [
  { uf: "AC", name: "Acre" },
  { uf: "AL", name: "Alagoas" },
  { uf: "AP", name: "Amapá" },
  { uf: "AM", name: "Amazonas" },
  { uf: "BA", name: "Bahia" },
  { uf: "CE", name: "Ceará" },
  { uf: "DF", name: "Distrito Federal" },
  { uf: "ES", name: "Espírito Santo" },
  { uf: "GO", name: "Goiás" },
  { uf: "MA", name: "Maranhão" },
  { uf: "MT", name: "Mato Grosso" },
  { uf: "MS", name: "Mato Grosso do Sul" },
  { uf: "MG", name: "Minas Gerais" },
  { uf: "PA", name: "Pará" },
  { uf: "PB", name: "Paraíba" },
  { uf: "PR", name: "Paraná" },
  { uf: "PE", name: "Pernambuco" },
  { uf: "PI", name: "Piauí" },
  { uf: "RJ", name: "Rio de Janeiro" },
  { uf: "RN", name: "Rio Grande do Norte" },
  { uf: "RS", name: "Rio Grande do Sul" },
  { uf: "RO", name: "Rondônia" },
  { uf: "RR", name: "Roraima" },
  { uf: "SC", name: "Santa Catarina" },
  { uf: "SP", name: "São Paulo" },
  { uf: "SE", name: "Sergipe" },
  { uf: "TO", name: "Tocantins" },
] as const;

export const collegeSuggestions: CollegeSuggestion[] = [
  {
    city: "São Paulo",
    name: "FATEC",
    mec: "4/5",
    advantages: ["Opções públicas", "Foco prático", "Boa presença regional"],
    uf: "SP",
  },
  {
    city: "Rio de Janeiro",
    name: "CEFET/RJ",
    mec: "4/5",
    advantages: ["Tradição técnica", "Pesquisa aplicada", "Boa base de engenharia"],
    uf: "RJ",
  },
  {
    city: "Belo Horizonte",
    name: "UFMG",
    mec: "5/5",
    advantages: ["Universidade pública", "Pesquisa forte", "Ecossistema tech local"],
    uf: "MG",
  },
  {
    city: "Remoto",
    name: "Universidade Aberta do Brasil",
    mec: "Variável",
    advantages: ["Opções EAD", "Polos regionais", "Boa opção para começar pesquisando"],
    uf: null,
    nacional: true,
  },
];
