/**
 * Mapa canônico de tecnologia para áreas de atuação.
 *
 * Fonte única: era um objeto inline em client/src/lib/technologyData.ts
 * (areaMap). Movido para shared/ para que o servidor (analisador de
 * LinkedIn, server/lib/skillNormalize.ts) e o cliente usem os mesmos
 * dados sem duplicação. O client reexporta como technologiesByArea.
 *
 * As chaves são nomes legíveis de tecnologia. Os valores são slugs de área
 * (a maioria casa com AREA_SLUGS de shared/areas.ts; alguns como "mainframe"
 * existem só no catálogo amplo de áreas e simplesmente não casam com as 22
 * áreas selecionáveis no analisador).
 */

export const TECH_AREA_MAP: Record<string, string[]> = {
  HTML: ["frontend"],
  CSS: ["frontend", "uxui"],
  JavaScript: ["frontend", "backend", "mobile", "fullstack", "blockchain"],
  TypeScript: ["frontend", "backend", "mobile", "fullstack", "blockchain"],
  React: ["frontend", "fullstack"],
  "Vue.js": ["frontend"],
  Angular: ["frontend"],
  "Next.js": ["frontend", "backend", "fullstack"],
  "Tailwind CSS": ["frontend", "uxui", "fullstack"],
  Sass: ["frontend", "uxui"],
  Vite: ["frontend", "devops"],
  Redux: ["frontend"],
  Webpack: ["frontend", "devops"],
  Storybook: ["frontend", "qa", "uxui"],
  Python: [
    "backend",
    "dados",
    "ia",
    "qa",
    "engenharia-dados",
    "analise-dados",
    "iot",
  ],
  "Node.js": ["backend", "frontend", "fullstack"],
  "Express.js": ["backend", "fullstack"],
  Java: ["backend", "mobile"],
  PHP: ["backend"],
  FastAPI: ["backend", "dados", "ia"],
  Django: ["backend", "dados"],
  "Spring Boot": ["backend", "mobile"],
  Go: ["backend", "devops", "blockchain"],
  Rust: ["backend", "ciberseguranca", "blockchain"],
  "C#": ["backend", "gamedev"],
  SQL: [
    "backend",
    "dados",
    "banco-de-dados",
    "engenharia-dados",
    "analise-dados",
    "analise-sistemas",
  ],
  GraphQL: ["backend", "frontend", "mobile", "fullstack"],
  PostgreSQL: [
    "backend",
    "dados",
    "fullstack",
    "banco-de-dados",
    "engenharia-dados",
  ],
  MySQL: ["backend", "dados", "banco-de-dados", "engenharia-dados"],
  MongoDB: [
    "backend",
    "dados",
    "fullstack",
    "banco-de-dados",
    "engenharia-dados",
  ],
  Redis: ["backend", "devops", "banco-de-dados"],
  Elasticsearch: [
    "backend",
    "dados",
    "devops",
    "banco-de-dados",
    "engenharia-dados",
  ],
  Docker: ["devops", "backend", "cloud", "fullstack", "sre", "infraestrutura"],
  Kubernetes: ["devops", "cloud", "sre"],
  Terraform: ["devops", "cloud", "sre", "infraestrutura"],
  Ansible: ["devops", "cloud", "sre", "infraestrutura"],
  "GitHub Actions": ["devops", "cloud"],
  Jenkins: ["devops", "qa"],
  Prometheus: ["devops", "cloud", "sre"],
  Grafana: ["devops", "cloud", "sre"],
  Kafka: ["backend", "devops", "dados", "engenharia-dados"],
  RabbitMQ: ["backend", "devops"],
  Cypress: ["qa", "frontend"],
  Playwright: ["qa", "frontend", "backend"],
  AWS: ["cloud", "devops", "sre", "infraestrutura"],
  "Google Cloud": ["cloud", "dados", "ia", "infraestrutura"],
  Azure: ["cloud", "devops", "infraestrutura"],
  Git: ["frontend", "backend", "dados", "mobile", "devops", "qa", "fullstack"],
  Linux: [
    "devops",
    "cloud",
    "ciberseguranca",
    "backend",
    "sre",
    "infraestrutura",
    "iot",
  ],
  Figma: ["uxui", "frontend", "produto"],
  "Power BI": ["dados", "produto", "analise-dados"],
  Flutter: ["mobile"],
  "React Native": ["mobile", "frontend"],
  Swift: ["mobile"],
  Kotlin: ["mobile"],
  R: ["dados", "analise-dados"],
  Spark: ["dados", "engenharia-dados"],
  Pandas: ["dados", "ia", "analise-dados"],
  NumPy: ["dados", "ia", "analise-dados"],
  TensorFlow: ["ia", "dados"],
  PyTorch: ["ia", "dados"],
  Unity: ["gamedev"],
  "Unreal Engine": ["gamedev"],
  Godot: ["gamedev"],
  "C++": ["backend", "gamedev", "iot"],
  Lua: ["gamedev", "backend"],
  Solidity: ["blockchain"],
  C: ["backend", "iot"],
  Arduino: ["iot"],
  "Apache Airflow": ["engenharia-dados", "dados"],
  dbt: ["engenharia-dados", "dados", "analise-dados"],
  Snowflake: ["dados", "engenharia-dados", "banco-de-dados", "analise-dados"],
  Tableau: ["analise-dados", "dados", "produto"],
  Looker: ["analise-dados", "dados"],
  Jira: ["gestao", "produto", "qa"],
  Trello: ["gestao", "produto"],
  Notion: ["gestao", "produto"],
  Confluence: ["gestao"],
  Ruby: ["backend", "fullstack"],
  Dart: ["mobile", "frontend"],
  Scala: ["backend", "dados", "engenharia-dados"],
  Julia: ["dados", "ia", "analise-dados"],
  MATLAB: ["dados", "analise-dados", "ia"],
  COBOL: ["mainframe", "backend"],
  Fortran: ["dados", "analise-sistemas"],
  Assembly: ["iot", "ciberseguranca"],
  Ada: ["backend", "iot"],
  "Visual Basic": ["backend", "analise-sistemas"],
  "Objective-C": ["mobile"],
  Elixir: ["backend", "fullstack"],
  Erlang: ["backend"],
  Haskell: ["backend"],
  Clojure: ["backend"],
  "F#": ["backend"],
  Groovy: ["backend", "devops", "qa"],
  Bash: ["devops", "sre", "infraestrutura", "backend"],
  PowerShell: ["devops", "infraestrutura", "ciberseguranca"],
  Perl: ["backend", "devops"],
  Svelte: ["frontend"],
  Nuxt: ["frontend", "fullstack"],
  Astro: ["frontend"],
  SolidJS: ["frontend"],
  Bootstrap: ["frontend", "uxui"],
  "Material UI": ["frontend", "uxui"],
  NestJS: ["backend", "fullstack"],
  Flask: ["backend", "dados", "ia"],
  Laravel: ["backend", "fullstack"],
  "Ruby on Rails": ["backend", "fullstack"],
  "ASP.NET Core": ["backend", "fullstack"],
  Phoenix: ["backend", "fullstack"],
  Quarkus: ["backend"],
  SwiftUI: ["mobile"],
  "Jetpack Compose": ["mobile"],
  Ionic: ["mobile", "frontend"],
  ".NET MAUI": ["mobile"],
  MariaDB: ["backend", "banco-de-dados", "engenharia-dados"],
  "SQL Server": ["backend", "banco-de-dados", "engenharia-dados"],
  Oracle: ["backend", "banco-de-dados", "engenharia-dados"],
  SQLite: ["backend", "mobile", "banco-de-dados"],
  Cassandra: ["backend", "banco-de-dados", "engenharia-dados"],
  DynamoDB: ["backend", "cloud", "banco-de-dados", "engenharia-dados"],
  Neo4j: ["backend", "banco-de-dados", "dados"],
  Firebase: ["mobile", "frontend", "fullstack", "backend"],
  Supabase: ["frontend", "fullstack", "backend"],
  "scikit-learn": ["dados", "ia", "analise-dados"],
  Keras: ["ia", "dados"],
  Hadoop: ["dados", "engenharia-dados"],
  Jupyter: ["dados", "ia", "analise-dados", "engenharia-dados"],
  "Hugging Face": ["ia", "dados"],
  LangChain: ["ia", "backend"],
  "IBM Cloud": ["cloud", "infraestrutura", "mainframe"],
  DigitalOcean: ["cloud", "devops", "infraestrutura"],
  "GitLab CI": ["devops", "sre", "qa"],
  Nginx: ["devops", "backend", "sre", "infraestrutura"],
  "Windows Server": ["devops", "infraestrutura"],
  Unix: ["devops", "infraestrutura", "sre"],
  VMware: ["devops", "infraestrutura", "cloud"],
  "Kali Linux": ["ciberseguranca"],
  Wireshark: ["ciberseguranca", "infraestrutura"],
  Nmap: ["ciberseguranca", "infraestrutura"],
  "Burp Suite": ["ciberseguranca"],
  Metasploit: ["ciberseguranca"],
  "OWASP ZAP": ["ciberseguranca", "qa"],
  Jest: ["qa", "frontend"],
  Vitest: ["qa", "frontend"],
  Selenium: ["qa"],
  JUnit: ["qa", "backend"],
  PyTest: ["qa", "backend", "dados"],
  Postman: ["qa", "backend"],
  "Adobe XD": ["uxui", "produto"],
  Sketch: ["uxui", "produto"],
  Canva: ["uxui", "produto"],
  Asana: ["gestao", "produto"],
};
