-- Uma assinatura ATIVA por usuario, garantida pelo banco.
--
-- NAO APLICAR ANTES DO DEPLOY DO CODIGO. Ver "BLOQUEIO RESOLVIDO" abaixo: o
-- caminho de codigo que esta migration quebrava ja foi corrigido (passou a usar
-- a RPC de 20260829110000), mas a correcao precisa estar SERVINDO em producao
-- antes do CREATE INDEX.
--
-- PROBLEMA. Nao existe hoje NENHUMA trava de banco contra duas linhas ativas do
-- mesmo usuario. A unica unicidade em public.subscriptions e sobre
-- provider_subscription_id (20260517231011_remote_schema.sql), que impede
-- duplicar a MESMA assinatura do provedor, nao duas assinaturas diferentes da
-- mesma pessoa. A protecao e toda de aplicacao, em tres lugares:
--
--   1. guard 409 no checkout            server/providers/stripe.ts
--   2. supersede na renovacao de boleto activate_subscription_exclusive
--                                       (era um UPDATE best-effort no
--                                        TypeScript ate 29/08/2026)
--   3. guard 409 de boleto pendente     server/providers/stripe.ts
--
-- O item 1 e uma checagem ler-depois-escrever: ele consulta antes de criar a
-- sessao de checkout, e entre a consulta e a linha que o webhook grava cabe um
-- fluxo de pagamento inteiro. O proprio comentario dele ja admite que multiplas
-- linhas ativas sao um estado possivel ("nada de .maybeSingle() aqui, ele ERRA
-- com multiplas linhas ativas"). Com um SEGUNDO provedor de pagamento criando
-- assinatura por um caminho proprio, os tres guards passam a ser tres copias da
-- mesma regra, e a primeira que alguem esquecer de replicar abre o buraco.
--
-- SOLUCAO. Indice unico PARCIAL sobre (user_id) onde o status concede acesso.
-- E a mesma forma da 20260730180000 (uma geracao ativa por usuario) e da
-- 20260716130000 (influencers_active_user_uidx): a regra passa a existir num
-- lugar que nenhum caminho de escrita novo pode contornar por esquecimento.
--
-- POR QUE ('active', 'trialing') E NAO OUTRO CONJUNTO. Esses sao exatamente os
-- status que concedem acesso Pro, e os quatro sitios independentes que decidem
-- isso concordam:
--
--   is_user_pro, `s.status in ('active','trialing')`
--     supabase/migrations/20260716130100_add_influencer_to_is_user_pro.sql:28
--   isProStatus()
--     server/providers/stripe.ts:121
--   guard de checkout duplicado
--     server/providers/stripe.ts:1067
--   ancora de periodo na renovacao de boleto
--     server/providers/stripe.ts, em onBoletoAsyncPaymentSucceeded
--   supersede na renovacao de boleto
--     supabase/migrations/20260829110000_activate_subscription_exclusive.sql
--
-- 'past_due' fica DE FORA de proposito. Ele aparece em varios `in('active',
-- 'trialing','past_due')` (server/providers/stripe.ts:1310,
-- server/routes/admin.ts:3205 e :4155), mas ali a pergunta e "existe assinatura
-- para operar sobre", nao "esta pessoa tem acesso": is_user_pro nega past_due.
-- Incluir past_due no indice travaria uma cobranca em recuperacao junto de uma
-- assinatura nova legitima, que e um estado real e nao um defeito.
--
-- BLOQUEIO RESOLVIDO. FALTA O DEPLOY DO CODIGO.
--
-- O bloqueio era este: a ativacao de boleto pago fazia DUAS escritas separadas,
-- sem transacao (flip da linha nova para 'active' e, SO DEPOIS, o UPDATE que
-- marcava as antigas como 'superseded'). Entre as duas, uma renovacao tinha
-- DUAS linhas 'active' do mesmo usuario, por construcao. Com este indice no
-- lugar, o primeiro UPDATE levantaria 23505, o handler lancaria, a compensacao
-- apagaria o billing_event, a Stripe reentregaria, encontraria o mesmo estado e
-- falharia de novo: laco permanente, com uma renovacao JA PAGA sem conceder
-- acesso.
--
-- As duas escritas viraram UMA chamada de `activate_subscription_exclusive`
-- (migration 20260829110000, ja aplicada no banco), que faz supersede e
-- ativacao na mesma transacao, na ordem supersede-primeiro, e e idempotente na
-- reentrega. A ordem que este indice exige passou a ser a ordem que o codigo
-- executa.
--
-- CONDICAO QUE FALTA: o codigo que chama a RPC precisa estar EM PRODUCAO antes
-- deste indice. Aplicar o indice com o backend antigo ainda servindo reabre
-- exatamente o laco descrito acima, porque e o backend antigo que faz as duas
-- escritas. A sequencia e: deploy do codigo verificado no Railway, e so entao
-- este CREATE INDEX.
--
-- PRE-CONDICAO VERIFICADA EM 29/08/2026, por consulta direta ao banco de
-- producao: ZERO usuarios com mais de uma linha em status ativo. Nenhuma
-- duplicata existente faz o CREATE INDEX falhar.
--
-- RE-VERIFICAR SE A APLICACAO ATRASAR. A medida vale para o instante em que foi
-- feita, e a condicao que ela afirma pode ser desfeita por qualquer ativacao
-- entre a medicao e o CREATE INDEX. A query esta na secao "Pre-checagem da
-- migration" do relatorio lote0-pagamentos-2026-08-29.md e precisa devolver
-- ZERO linhas. Se devolver qualquer linha, o indice falha na criacao e as
-- duplicatas precisam ser resolvidas primeiro (decisao de negocio, nao de
-- migration).
--
-- Sem CONCURRENTLY, seguindo a 20260730180000: public.subscriptions e pequena e
-- o lock breve de um CREATE INDEX nao justifica abrir mao de poder rodar dentro
-- de uma transacao.
--
-- ADITIVA: cria indice, nao altera nem remove dado. Isenta da janela de
-- migration destrutiva (CLAUDE.md). Rollback e DROP INDEX.
--
-- Idempotente: pode rodar mais de uma vez sem efeito colateral.

CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_one_active_per_user
  ON public.subscriptions (user_id)
  WHERE status IN ('active', 'trialing');
