-- Adiciona 8 novas areas ao catalogo na tabela `areas`, alinhando com o
-- fallback `areasTI` (client/src/lib/data.ts). Areas: Analise de Dados/BI,
-- Engenharia de Dados, Banco de Dados/DBA, SRE, Suporte e Infraestrutura/Redes,
-- Analise de Sistemas, Blockchain/Web3 e IoT/Sistemas Embarcados.
--
-- Salarios pesquisados no mercado BR (Glassdoor / salario.com.br, 2025-2026).
-- Cursos gratuitos sao recursos reais (Cisco Networking Academy, DataTalks
-- Zoomcamp, CryptoZombies, Alchemy University, Arduino, Curso em Video, etc.).
--
-- Ordem: as areas entram no fim (sort_order 15 a 22), sem precisar de shift,
-- pois o maximo atual e 14 (gamedev). ON CONFLICT (slug) DO NOTHING garante
-- idempotencia: rodar a migration mais de uma vez nao duplica nem altera.

BEGIN;

INSERT INTO public.areas (
  slug, name, short_description, full_description, daily_tasks, profile_indicated,
  skills, tools, average_salary, free_courses, initial_roadmap, projects,
  essential_terms, initial_tips, roles, tag, tag_class, icon, color,
  is_pro, is_published, sort_order
) VALUES
(
  'analise-dados',
  'Análise de Dados / BI',
  'Transforma dados em relatórios, dashboards e insights para apoiar decisões de negócio.',
  'O analista de dados (ou de BI) coleta, limpa e organiza dados de diferentes fontes para responder perguntas de negócio. Cria dashboards e relatórios que ajudam times e gestores a decidir com base em números, não em achismo. É uma das principais portas de entrada na área de dados: exige menos matemática avançada que ciência de dados, mas muito SQL, visualização e capacidade de contar histórias com os dados.',
  '["Escrever consultas SQL para extrair dados de bancos","Limpar e organizar planilhas e tabelas","Criar dashboards no Power BI, Looker Studio ou Tableau","Traduzir perguntas de negócio em métricas e indicadores","Apresentar resultados e insights para times e gestores"]'::jsonb,
  'Combina com quem gosta de números, tem curiosidade por entender o porquê das coisas e sabe se comunicar bem. Não precisa de matemática pesada, mas precisa de organização e atenção ao detalhe.',
  '["SQL (consultas, joins e agregações)","Excel ou Planilhas avançado","Power BI, Looker Studio ou Tableau","Estatística descritiva básica","Storytelling com dados","Inglês para leitura"]'::jsonb,
  '["SQL","Power BI","Looker Studio","Tableau","Excel / Google Sheets","Python (pandas) básico"]'::jsonb,
  '{"label":"Júnior R$ 3.000 a R$ 5.000, Pleno R$ 5.500 a R$ 8.300, Sênior R$ 9.000 a R$ 13.000 (Glassdoor 2026)","difficulty":3}'::jsonb,
  '["Microsoft Learn: trilha de Power BI (gratuita)","Curso em Vídeo: MySQL (Gustavo Guanabara)","Kaggle Learn: Pandas e Data Visualization (gratuito, em inglês)","DIO: bootcamps gratuitos de Análise de Dados"]'::jsonb,
  '["Aprender SQL do básico ao intermediário","Dominar Excel ou Google Sheets","Aprender uma ferramenta de BI (Power BI é a mais pedida)","Estudar estatística descritiva básica","Construir 2 ou 3 dashboards com dados públicos","Publicar os projetos no GitHub ou portfólio"]'::jsonb,
  '["Dashboard de vendas com dados públicos","Análise de uma base do governo (dados.gov.br)","Relatório de métricas de um e-commerce fictício"]'::jsonb,
  '["SQL","Dashboard","KPI","ETL","Data Viz","Query"]'::jsonb,
  'Foque em SQL e em uma ferramenta de BI antes de qualquer coisa. Use datasets reais e sempre explique o insight, não só mostre o gráfico. Saber contar a história por trás dos números vale mais que dominar dez ferramentas.',
  '["Analista de Dados Júnior","Analista de BI","Analista de Dados Pleno","Analista de Dados Sênior"]'::jsonb,
  'Análise de Dados / BI',
  'tag-dados',
  '📊',
  NULL,
  false,
  true,
  15
),
(
  'engenharia-dados',
  'Engenharia de Dados',
  'Constrói e mantém a infraestrutura e os pipelines que levam dados até quem analisa.',
  'O engenheiro de dados é quem constrói os caminhos por onde os dados passam. Cria pipelines que coletam, transformam e armazenam grandes volumes de dados de forma confiável, para que analistas e cientistas tenham dados limpos e prontos para usar. É uma área mais técnica e próxima do back-end, com salários altos e demanda em alta, puxada por empresas que querem se tornar orientadas a dados.',
  '["Construir e manter pipelines de dados (ETL e ELT)","Modelar tabelas e data warehouses","Trabalhar com bancos SQL e ferramentas como dbt e Spark","Automatizar e monitorar a ingestão de dados","Garantir qualidade, governança e disponibilidade dos dados"]'::jsonb,
  'Combina com quem gosta da parte de engenharia e de programação, tem paciência para resolver problemas de dados sujos e se importa com confiabilidade e organização. Mais código e infraestrutura, menos gráficos.',
  '["SQL avançado","Python","Modelagem de dados e data warehouse","Pipelines ETL e ELT (Airflow, dbt)","Cloud (AWS, GCP ou Azure)","Spark e processamento distribuído"]'::jsonb,
  '["Python","SQL","Apache Airflow","dbt","Apache Spark","BigQuery / Snowflake","Docker","AWS / GCP"]'::jsonb,
  '{"label":"Júnior R$ 5.000 a R$ 8.500, Pleno R$ 9.000 a R$ 15.000, Sênior acima de R$ 20.000 (Glassdoor 2026)","difficulty":4}'::jsonb,
  '["Data Engineering Zoomcamp (DataTalks.Club, gratuito, coorte de janeiro)","Databricks Customer Academy: cursos gratuitos em português","Data Science Academy: Fundamentos de Engenharia de Dados (gratuito, com certificado)","Curso em Vídeo: Python (base de programação)"]'::jsonb,
  '["Aprender Python e SQL com solidez","Entender modelagem de dados e data warehouse","Aprender a construir pipelines (ETL e ELT)","Estudar uma cloud (BigQuery é um bom começo)","Aprender Docker e orquestração com Airflow","Construir um pipeline completo de ponta a ponta"]'::jsonb,
  '["Pipeline que coleta dados de uma API e salva num banco","ETL de arquivos CSV para um data warehouse","Pipeline agendado com Airflow e dbt"]'::jsonb,
  '["Pipeline","ETL","Data Warehouse","Data Lake","Orquestração","Batch e Streaming"]'::jsonb,
  'Engenharia de dados não costuma ser a primeira porta de entrada: vale ter base de programação (Python) e SQL antes. Domine um banco de dados e aprenda a versionar e automatizar tudo. O Zoomcamp gratuito é um dos melhores caminhos práticos.',
  '["Engenheiro de Dados Júnior","Engenheiro de Dados Pleno","Engenheiro de Dados Sênior","Arquiteto de Dados"]'::jsonb,
  'Engenharia de Dados',
  'tag-dados',
  '🛠️',
  NULL,
  false,
  true,
  16
),
(
  'banco-de-dados',
  'Banco de Dados / DBA',
  'Cuida do armazenamento, performance, segurança e integridade dos bancos de dados.',
  'O administrador de banco de dados (DBA) é responsável por manter os bancos de dados de uma empresa funcionando bem: rápidos, seguros, disponíveis e sem perda de dados. Ajusta consultas lentas, faz backups, controla acessos e planeja a estrutura dos dados. É uma área estável e essencial, presente em praticamente toda empresa que guarda informação, do banco ao e-commerce.',
  '["Monitorar e otimizar a performance de consultas","Planejar e testar rotinas de backup e recuperação","Controlar acessos, usuários e permissões","Modelar e ajustar a estrutura de tabelas e índices","Garantir segurança, disponibilidade e integridade dos dados"]'::jsonb,
  'Combina com quem é organizado, metódico, gosta de lógica e se preocupa com segurança e confiabilidade. Tem paciência para investigar problemas e prefere estabilidade a novidade constante.',
  '["SQL avançado","Modelagem de dados (normalização)","Administração de SGBD (PostgreSQL, MySQL, Oracle ou SQL Server)","Tuning e otimização de consultas","Backup, recuperação e segurança","Noções de Linux"]'::jsonb,
  '["PostgreSQL","MySQL","SQL Server","Oracle","MongoDB","Linux"]'::jsonb,
  '{"label":"Júnior R$ 4.500 a R$ 7.600, Pleno R$ 8.000 a R$ 11.700, Sênior R$ 12.000 a R$ 15.000 (Glassdoor 2026)","difficulty":4}'::jsonb,
  '["Curso em Vídeo: MySQL (Gustavo Guanabara)","W3Schools: SQL Tutorial (gratuito, em inglês)","Microsoft Learn: trilhas de SQL Server e Azure SQL (gratuitas)","Oracle Learning Explorer (gratuito)"]'::jsonb,
  '["Aprender SQL do básico ao avançado","Entender modelagem e normalização de dados","Escolher e aprofundar em um SGBD (PostgreSQL é ótimo começo)","Estudar índices, tuning e planos de execução","Aprender backup, recuperação e controle de acesso","Praticar em um banco real com volume de dados"]'::jsonb,
  '["Modelar o banco de um sistema de e-commerce","Otimizar consultas lentas em uma base grande","Configurar rotina de backup e restauração"]'::jsonb,
  '["SGBD","Índice","Normalização","Backup","Tuning","Transação"]'::jsonb,
  'Comece dominando SQL de verdade, depois aprofunde em um banco específico. PostgreSQL é gratuito, robusto e muito pedido. Entender índices e planos de execução é o que separa um DBA bom de um iniciante.',
  '["DBA Júnior","Administrador de Banco de Dados","DBA Pleno","DBA Sênior"]'::jsonb,
  'Banco de Dados / DBA',
  'tag-dados',
  '🗄️',
  NULL,
  false,
  true,
  17
),
(
  'sre',
  'SRE (Site Reliability Engineering)',
  'Mantém sistemas no ar com confiabilidade, automação e monitoramento em escala.',
  'Site Reliability Engineering (SRE) é a junção de software com operações: o profissional usa programação para automatizar a operação e garantir que sistemas grandes fiquem estáveis, rápidos e disponíveis. Cuida de monitoramento, resposta a incidentes, capacidade e automação de infraestrutura. Surgiu no Google e é muito valorizado, costuma exigir experiência prévia em desenvolvimento ou infraestrutura, com salários altos.',
  '["Monitorar disponibilidade, latência e erros dos sistemas","Automatizar tarefas de operação e infraestrutura","Responder a incidentes e fazer post-mortems","Definir e acompanhar SLOs, SLIs e error budgets","Melhorar escalabilidade e resiliência das aplicações"]'::jsonb,
  'Combina com quem gosta de programar e de infraestrutura ao mesmo tempo, mantém a calma sob pressão e se importa com automação e confiabilidade. Costuma ser um passo depois de dev ou DevOps, não a primeira vaga.',
  '["Linux e redes","Uma linguagem de programação (Python ou Go)","Containers e Kubernetes","Observabilidade (logs, métricas e tracing)","CI/CD e infraestrutura como código","Resposta a incidentes"]'::jsonb,
  '["Kubernetes","Docker","Prometheus","Grafana","Terraform","AWS / GCP","Git"]'::jsonb,
  '{"label":"Júnior R$ 5.000 a R$ 8.000, Pleno R$ 8.400 a R$ 17.000, Sênior R$ 14.000 a R$ 21.000 (Glassdoor 2026)","difficulty":5}'::jsonb,
  '["Google SRE Books (sre.google/books, gratuitos online em inglês)","Google Cloud: SRE e DevOps Engineer (Coursera, modo audit gratuito)","LinuxTips: Descomplicando Docker e Kubernetes (YouTube, gratuito)","KodeKloud: labs gratuitos de Linux e Kubernetes"]'::jsonb,
  '["Dominar Linux e fundamentos de redes","Aprender uma linguagem (Python ou Go)","Entender containers e Kubernetes","Estudar observabilidade (Prometheus e Grafana)","Aprender infraestrutura como código (Terraform)","Estudar SLOs, SLIs e cultura de confiabilidade"]'::jsonb,
  '["Subir uma aplicação em Kubernetes com monitoramento","Criar dashboards de métricas com Prometheus e Grafana","Automatizar deploy com pipeline CI/CD e infraestrutura como código"]'::jsonb,
  '["SLO","SLI","Error Budget","Observabilidade","Incidente","Toil"]'::jsonb,
  'SRE raramente é a primeira vaga: tenha base de programação ou infraestrutura antes. Os livros de SRE do Google são gratuitos e a melhor referência. Foque em automação, pois o objetivo é eliminar trabalho manual repetitivo.',
  '["Site Reliability Engineer Júnior","Site Reliability Engineer Pleno","Site Reliability Engineer Sênior","Platform Engineer"]'::jsonb,
  'SRE',
  'tag-devops',
  '⚙️',
  NULL,
  false,
  true,
  18
),
(
  'infraestrutura',
  'Suporte e Infraestrutura / Redes',
  'Mantém computadores, servidores e redes funcionando no dia a dia da empresa.',
  'A área de suporte e infraestrutura cuida de tudo que faz a TI da empresa funcionar: computadores, servidores, redes, impressoras e acessos. É uma das portas de entrada mais acessíveis em tecnologia, ótima para quem está começando, pois dá visão ampla de como tudo se conecta e abre caminho para áreas como redes, cloud, DevOps e cibersegurança. O salário inicial é mais baixo que o de dev, mas a barreira de entrada também é menor.',
  '["Atender chamados e resolver problemas de usuários","Instalar e configurar computadores, sistemas e impressoras","Administrar redes, Wi-Fi e acessos","Monitorar servidores e serviços","Documentar procedimentos e gerenciar ativos de TI"]'::jsonb,
  'Combina com quem gosta de resolver problemas práticos, tem paciência para atender pessoas e curiosidade para entender como máquinas e redes funcionam. Ótima primeira porta para quem quer entrar logo no mercado.',
  '["Hardware e sistemas operacionais (Windows e Linux)","Redes (TCP/IP, DNS, DHCP e Wi-Fi)","Atendimento e comunicação","Noções de servidores e cloud","Active Directory e gestão de usuários","Resolução de problemas"]'::jsonb,
  '["Windows","Linux","Ferramentas de chamados (GLPI, Jira)","Switches e roteadores","Active Directory","VMware / VirtualBox"]'::jsonb,
  '{"label":"Júnior R$ 2.300 a R$ 4.000, Pleno R$ 4.500 a R$ 6.000, Sênior R$ 6.500 a R$ 9.000 (Glassdoor 2026)","difficulty":2}'::jsonb,
  '["Cisco Networking Academy: Skills for All (cursos gratuitos de redes)","Fundação Bradesco: Montagem e Manutenção de Computadores (gratuito)","Google IT Support (Coursera, modo audit gratuito)","Curso em Vídeo: Linux para iniciantes (gratuito)"]'::jsonb,
  '["Aprender hardware e montagem de computadores","Dominar Windows e o básico de Linux","Estudar fundamentos de redes (TCP/IP, DNS e DHCP)","Tirar uma certificação inicial (Cisco CCNA introdutório)","Aprender administração de usuários e servidores","Evoluir para redes, cloud ou cibersegurança"]'::jsonb,
  '["Montar uma pequena rede doméstica ou de laboratório","Configurar um servidor de arquivos em Linux","Documentar o inventário e os procedimentos de um setor"]'::jsonb,
  '["TCP/IP","DNS","DHCP","Active Directory","Chamado","Servidor"]'::jsonb,
  'É a porta de entrada mais acessível da TI. Aproveite para ver tudo de perto e descobrir o que mais gosta. Os cursos gratuitos da Cisco e da Fundação Bradesco são um ótimo começo. Use o suporte como trampolim para redes, cloud ou segurança.',
  '["Analista de Suporte Técnico","Analista de Infraestrutura Júnior","Analista de Redes","Administrador de Sistemas"]'::jsonb,
  'Suporte e Infraestrutura / Redes',
  'tag-devops',
  '🖥️',
  NULL,
  false,
  true,
  19
),
(
  'analise-sistemas',
  'Análise de Sistemas',
  'Faz a ponte entre as necessidades do negócio e a solução técnica que será construída.',
  'O analista de sistemas entende o problema do negócio e o traduz em requisitos claros para o time de desenvolvimento. Levanta necessidades com usuários, documenta processos, modela soluções e acompanha a entrega para garantir que o que foi construído resolve o problema certo. É uma área que mistura tecnologia, comunicação e visão de processos, ótima para quem gosta de organizar e conversar com pessoas.',
  '["Levantar requisitos com usuários e áreas de negócio","Documentar processos, regras e fluxos","Modelar soluções (diagramas, UML e casos de uso)","Alinhar expectativas entre negócio e desenvolvimento","Acompanhar testes e validar entregas"]'::jsonb,
  'Combina com quem gosta de organizar ideias, conversar com pessoas e entender processos. Une raciocínio lógico com boa comunicação. Ideal para quem curte tecnologia mas não quer passar o dia inteiro programando.',
  '["Levantamento e análise de requisitos","Modelagem de processos e UML","Lógica de programação e SQL básico","Comunicação e escrita clara","Metodologias ágeis (Scrum e Kanban)","Visão de negócio"]'::jsonb,
  '["Jira","Confluence","Figma / Miro","Diagramas (UML e BPMN)","SQL","Trello"]'::jsonb,
  '{"label":"Júnior R$ 3.200 a R$ 6.000, Pleno R$ 5.600 a R$ 9.600, Sênior R$ 11.000 a R$ 18.000 (Glassdoor 2026)","difficulty":3}'::jsonb,
  '["Fundação Bradesco: Análise de Sistemas e UML (gratuito)","Curso em Vídeo: Algoritmos e Lógica de Programação (gratuito)","DIO: bootcamps gratuitos de fundamentos","Coursera: Engenharia de Requisitos (modo audit gratuito)"]'::jsonb,
  '["Entender lógica de programação e SQL básico","Aprender levantamento e documentação de requisitos","Estudar modelagem de processos e UML","Conhecer metodologias ágeis (Scrum e Kanban)","Praticar escrevendo requisitos e casos de uso","Construir um portfólio de documentação de projetos"]'::jsonb,
  '["Documentar os requisitos de um app real","Modelar o fluxo de um processo em BPMN","Escrever casos de uso e histórias de usuário de um sistema"]'::jsonb,
  '["Requisito","UML","Caso de Uso","Stakeholder","Backlog","Processo"]'::jsonb,
  'Comunicação é tão importante quanto a parte técnica aqui. Aprenda a fazer boas perguntas e a documentar com clareza. Saber um pouco de programação e SQL ajuda muito a conversar com o time de desenvolvimento.',
  '["Analista de Sistemas Júnior","Analista de Requisitos","Analista de Negócios","Analista de Sistemas Sênior"]'::jsonb,
  'Análise de Sistemas',
  'tag-gestao',
  '📋',
  NULL,
  false,
  true,
  20
),
(
  'blockchain',
  'Blockchain / Web3',
  'Desenvolve contratos inteligentes e aplicações descentralizadas sobre blockchain.',
  'O desenvolvedor blockchain cria aplicações que rodam em redes descentralizadas, como a Ethereum. Escreve contratos inteligentes (smart contracts) que executam regras automaticamente e sem intermediários, usados em finanças (DeFi), tokens, NFTs e identidade digital. É uma área de nicho, mais volátil, mas com salários competitivos e demanda puxada por projetos cripto e iniciativas como o Drex do Banco Central.',
  '["Escrever e testar contratos inteligentes (Solidity)","Integrar aplicações web com a blockchain","Auditar e cuidar da segurança dos contratos","Trabalhar com carteiras, tokens e padrões (ERC-20 e ERC-721)","Acompanhar gás, custos e otimização on-chain"]'::jsonb,
  'Combina com quem tem base de programação, curiosidade por finanças e tecnologia descentralizada e tolerância a um mercado volátil. Segurança é levada a sério, pois um erro em contrato pode custar caro.',
  '["Solidity","Lógica de programação e JavaScript/TypeScript","Conceitos de blockchain e criptografia","Smart contracts e padrões ERC","Web3 (ethers.js, wagmi)","Segurança e auditoria de contratos"]'::jsonb,
  '["Solidity","Hardhat / Foundry","ethers.js","MetaMask","Remix IDE","Node.js"]'::jsonb,
  '{"label":"Júnior R$ 4.000 a R$ 8.000, Pleno R$ 8.000 a R$ 12.000, Sênior acima de R$ 15.000 (Glassdoor 2026)","difficulty":4}'::jsonb,
  '["CryptoZombies (gratuito, Solidity interativo no navegador)","Alchemy University: Solidity e Ethereum Developer Bootcamp (gratuito)","freeCodeCamp: curso de Solidity e smart contracts (YouTube, Patrick Collins)","Ethereum.org: documentação para desenvolvedores (gratuita)"]'::jsonb,
  '["Aprender lógica de programação e JavaScript","Entender como funciona uma blockchain","Aprender Solidity com o CryptoZombies","Criar e fazer deploy de contratos de teste (Remix)","Integrar um contrato com uma aplicação web (Web3)","Estudar segurança e auditoria de smart contracts"]'::jsonb,
  '["Token ERC-20 próprio em rede de teste","Aplicação de votação on-chain","Marketplace simples de NFT (ERC-721)"]'::jsonb,
  '["Smart Contract","Solidity","Gas","Token","DApp","Wallet"]'::jsonb,
  'Tenha base sólida de programação antes de partir para blockchain. Comece pelo CryptoZombies e pela Alchemy University, ambos gratuitos. Segurança é prioridade absoluta, pois um bug pode causar prejuízo irreversível, então estude auditoria desde cedo.',
  '["Desenvolvedor Blockchain Júnior","Desenvolvedor Solidity","Engenheiro Web3","Desenvolvedor Blockchain Sênior"]'::jsonb,
  'Blockchain / Web3',
  'tag-backend',
  '⛓️',
  NULL,
  false,
  true,
  21
),
(
  'iot',
  'IoT / Sistemas Embarcados',
  'Programa o software que roda dentro de dispositivos físicos e objetos conectados.',
  'Sistemas embarcados e IoT (Internet das Coisas) são o software que roda dentro de dispositivos físicos: de uma máquina de café e um carro até sensores industriais e dispositivos vestíveis. O profissional programa microcontroladores, integra sensores, cuida de comunicação e de consumo de energia, e conecta os dispositivos à internet. Combina programação com eletrônica e tem demanda crescente com a expansão da IoT e da indústria 4.0.',
  '["Programar microcontroladores (firmware em C e C++)","Integrar sensores, atuadores e periféricos","Implementar comunicação (Wi-Fi, Bluetooth e MQTT)","Otimizar consumo de memória e energia","Testar e depurar hardware e software juntos"]'::jsonb,
  'Combina com quem gosta de programação e também de eletrônica e do mundo físico, tem paciência para depurar problemas de hardware e curte ver o código controlando algo real. Matemática e lógica ajudam bastante.',
  '["Linguagem C e C++","Eletrônica básica","Microcontroladores (Arduino, ESP32 e STM32)","Protocolos de comunicação (I2C, SPI e MQTT)","RTOS e gerenciamento de memória","Depuração de hardware"]'::jsonb,
  '["Arduino IDE","ESP32","Raspberry Pi","C / C++","PlatformIO","Osciloscópio e multímetro"]'::jsonb,
  '{"label":"Júnior R$ 4.000 a R$ 7.000, Pleno R$ 7.000 a R$ 13.000, Sênior R$ 12.000 a R$ 18.000 (Glassdoor 2026)","difficulty":4}'::jsonb,
  '["Arduino: tutoriais e documentação oficiais (gratuitos)","Cisco Networking Academy: Introduction to IoT (gratuito)","Curso em Vídeo: Linguagem C (Gustavo Guanabara, base de firmware)","Portal Embarcados: artigos e tutoriais gratuitos (embarcados.com.br)"]'::jsonb,
  '["Aprender lógica de programação e linguagem C","Estudar eletrônica básica","Começar com Arduino e projetos simples","Evoluir para ESP32 e conectividade (Wi-Fi e MQTT)","Aprender protocolos de comunicação (I2C e SPI)","Construir um projeto de IoT completo conectado à nuvem"]'::jsonb,
  '["Estação meteorológica com sensores e Wi-Fi","Automação de luz ou irrigação com ESP32","Dispositivo que envia dados para um dashboard na nuvem"]'::jsonb,
  '["Microcontrolador","Firmware","Sensor","GPIO","MQTT","RTOS"]'::jsonb,
  'Comece com Arduino, que é barato e tem comunidade enorme, depois migre para o ESP32 (Wi-Fi embutido). Aprenda C de verdade, pois é a linguagem do firmware. Ter o hardware na mão e construir projetos físicos é o que mais acelera o aprendizado.',
  '["Desenvolvedor de Firmware Júnior","Engenheiro de Sistemas Embarcados","Desenvolvedor IoT","Engenheiro de Firmware Sênior"]'::jsonb,
  'IoT / Sistemas Embarcados',
  'tag-backend',
  '📡',
  NULL,
  false,
  true,
  22
)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
